### ISSUE TITLE
Get parser to run on all FEC regulations

### ISSUE THREAD

**Issue by anthonygarvan** [18F/fec-eregs#1]
Upon running the 18F/regulations-parser on FEC regulations (title 11), there were 50 regulations that parsed properly (at least, completed parsing- have not manually verified accuracy), and 3 that failed. This issue may be closed once all 53 regulations can be parsed.

**Comment by porta-antiporta** [comment]
Closing as we have the initial pass of parsing complete: https://fec-eregs.apps.cloud.gov/
