### ISSUE TITLE
Links to defined terms

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#10]
https://fec-eregs.apps.cloud.gov/100-19/2015-annual-100#100-19-a

"Document," "election," "commission" and "states" are linked as defined terms but these are not definitions we want.  

![links to defined terms](https://cloud.githubusercontent.com/assets/11817734/13260389/36455c9c-da29-11e5-8b8e-4b0782418f41.png)

**Comment by porta-antiporta** [comment]
https://trello.com/c/FC2ZnIqk/25-fec-eregs-links-to-defined-terms

**Comment by PaulClark2** [comment]
Another example:  Some definitions aren't really definitions (e.g., in 100.22(b), "defeat" is linked to 100.22(a), which doesn't define that term).

**Comment by PaulClark2** [comment]
Originally posted in #24:   Some of the linked definitions don't accurately reflect the term as used in context (e.g., in 1.1(b), "Act" is linked to the definition of FECA, even where the word is used in term "Privacy Act"; in 100.1, "Election" and "Commission" are individually linked even when used within the phrases "Federal Election Commission" and "Federal Election Campaign Act")

**Comment by tadhg-ohiggins** [comment]
“United States”, “Federal Election Commission”, and “Federal Election Campaign Act” have been excluded as phrases so none of their words will be highlights. For “document”, we are now showing the first paragraph of the definition of document in the sidebar.
