### ISSUE TITLE
Derivative Search - Search should recognize plurals, past tense etc as a single term

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#106]
Currently when a user enters filing vs filings, the search yields different results.  The search should yield the same results.

``` Gherkin

Given a user has entered the a plural search term
When they trigger the search
Then they should receive the same results as if the user entered a singular search term

Given a user has entered a search term in the past tense
When they trigger the search
Then they should receive the same results as the present tense
```

**Comment by nickykrause** [comment]
(cc: @jenniferthibault, @emileighoutlaw) 

The design team just met to review legal issues for this sprint, and we're wondering: Will this issue also be resolved by turning on stemming functionality, or is this different?

**Comment by jenniferthibault** [comment]
Quick chatted with @anthonygarvan : it's the same. Closed https://github.com/18F/fec-eregs/issues/293 to reflect that.

**Comment by noahmanger** [comment]
Stemming enabled in productin.
