### ISSUE TITLE
Legal landing: Regulations

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-eregs#111]
Hi @amykort @amypike! We need a little sentence to introduce 11 CFR on the legal landing page. I was thinking something like:

>  ​**Regulations**
> The rules that apply to federal campaign finance law are outlined in Title 11 of the Code of Federal Regulations (CFR). This archive contains a full-text version of 11 CFR, which the FEC administers and enforces.

Thoughts? Edits? Can we say that?

**Comment by AmyKort** [comment]
Right now we say: The Commission promulgates regulations and publishes them in the Federal Register throughout the year. All of the Commission’s regulations are published in an annual printed edition of Title 11 of the Code of Federal Regulations (CFR). The printed version of the CFR is current as of January 1 of the year of publication. The Government Printing Office also maintains an electronic version of the CFR — the eCFR — which is updated daily and includes all Federal Register notices published as recently as the previous day. 

I'm not wedded to that, but it does have the benefit of pointing out that we're looking at a particular edition of the regulations. 

Also, I think it might be too general to say that "the rules that apply to campaign finance law are outlined in  . . ." Can we focus more on the idea that the commission administers and enforces the FECA and issues (or enacts? or something?) regulations, which are included in Title 11?

**Comment by emileighoutlaw** [comment]
Ahhh, I hear you Amy. Working now toward something that takes into account all the awesome info you have above but doesn't sound too much like a mission statement or explanation of FEC operations; we want to focus on introducing this specific resource. 

How about something along the lines of:

> As part of its role administering and enforcing campaign finance law, the Commission issues regulations, which are published every year in Title 11 of the Code of Federal Regulations (CFR). This archive contains a full-text version of 11 CFR, as published January 1, 2016.

**Comment by AmyKort** [comment]
Looks good to me!

**Comment by AmyKort** [comment]
Or, how about we just say as part of its role in administering campaign finance law...

**Comment by emileighoutlaw** [comment]
Love it!
