### ISSUE TITLE
Mobile - Hamburger menu

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#117]
<img width="100" alt="two menus" src="https://cloud.githubusercontent.com/assets/16668007/15865695/67913774-2ca1-11e6-9694-aafc05a4ef79.png">
When viewing a regulation, there are two hamburger menus.
* Menu to navigate to the different sections of beta (campaign, registration/reporting, legal resources)
* Menu to navigate the different sections within the currently selected regulation.

Currently, when clicking the menu to navigate to a different section of beta, there is no response.

What should happen is:

State: 
* User is on mobile viewing a regulation.  
* Both menus are collapsed

Trigger:
* User looks to expand the top menu (navigate beta)

Outcome:
* The different sections of beta.fec are rendered and user can select one to navigate there.

Out of scope: Reconciling whether having 2 hamburger menus is confusing to the user.

- [ ] disable mega menu on desktop widths

**Comment by edmullen** [comment]
Given the out-of-scope statement, this may not apply, but I want to call out [this comment](https://github.com/18F/fec-eregs/issues/114#issuecomment-224628582) on #114. I am recommending that we remove the search altogether within the eregs app and stick with the web app search as currently stands. That means the magnifying glass icon is not needed on mobile and neither is the table of content icon, the bulleted list/second hamburger-like icon since we will not have any tabs. The open/close icon is the only eregs side panel control needed.

**Comment by porta-antiporta** [comment]
@anthonygarvan @edmullen The prize for this story though is still ensuring the menu for navigating around beta.fec is functional.  

Does responsive design mean removing those controls from desktop (as part of #114) would also result in them being gone on mobile?

**Comment by porta-antiporta** [comment]
And am _just_ realizing, we don't have 2 hamburger menus in mobile today.  We have one hamburger menu, and another control to get to the table of contents.  But the icons share a lot in common. :weary:

**Comment by edmullen** [comment]
Yes, I think the TOC bulleted list icon and the search magnifying glass icon should be removed from both. [See here for desktop](https://github.com/18F/fec-eregs/issues/114#issuecomment-224628582). So no tabs on desktop. No side-rail icon tabs on mobile besides the arrow open/close.

**Comment by adborden** [comment]
The current state of the work is on `feature/nav-menu`
https://fec-adborden-eregs.18f.gov
https://github.com/18F/fec-eregs/tree/feature/nav-menu

**Comment by adborden** [comment]
After a brief discussion today, we'll disable the mega menu on desktop (added above). Currently the menu is missing some styling, so there's some work involved in getting it working. We'll hold off on any investment in the nav menus until the next iteration of the mobile menu has been finalized.
