### ISSUE TITLE
Content for AO landing page

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#118]
On the [AO landing page](https://gsa.invisionapp.com/share/NP7IRPOWD#/screens/163806620), there are three sections where we need to create content:
- [ ] Introduction/Initial description to what AOs are
- [ ] Introduction to requesting an AO
- [ ] Introduction to currently Pending AOs

Look to complete defining the content in Sprint 15 so that we can implement in Sprint 16.

**Comment by porta-antiporta** [comment]
@edmullen the Get Started button in the Requesting AOs section points to fec.gov initially, is that correct?

**Comment by jeanninehunter** [comment]
Legal resources landing draft referenced in today's legal sprint grooming/planning meeting: https://docs.google.com/document/d/1l7PKLJvLmBV0cFONvsIIvee3uDEs2dK_q8JeOqHGAh0/edit#heading=h.qgmk0q45qngu

**Comment by edmullen** [comment]
@emileigh said that we can proceed with linking the button under "Requesting advisory opinions" to [this page on the current FEC site](http://www.fec.gov/pages/brochures/ao.shtml).

Previous testing suggested "Get started" is a poor choice for this button because it sounds like you can make the request online, which you can not do. You just get info about how to do it.

**Comment by emileighoutlaw** [comment]
@amykort — we talked about this in our last content meeting (linking things from beta over to FEC.gov). Just triple checking that this is 👍 to do!

Re: button content: How about `More information` ?

@jeanninehunter: Thanks for posting the legal landing page draft! Do you also have an  Advisory Opinion landing page draft that you can link in here? 

Last thing: We had talked about designing a banner for FEC.gov, when folks click over to the legacy site. Something that says "Take me back to betaFEC." Do we want to try and do that? I'm not sure how heavy a lift it is technically, but it would be really helpful to our users. Could bring in Noah and Jen to consult on styles. I'm happy to whip up some content.

**Comment by AmyKort** [comment]
Yes, we are good with the plan to link things from beta over to fec.gov. Button content looks good. We also think the "get back to beta" banner is a good idea of that's possible. Thanks!

@wluoFEC

**Comment by porta-antiporta** [comment]
- Content for AO Overview has been approved.
- How to request an AO, we just to link to the brochure
