### ISSUE TITLE
Parts 9405 to 9430 (Chapter II Election Assistance Commission)

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#12]
@porta-antiporta follow up from Slack, we haven't found any missing parts but there are parts in eRegulations that are not FEC regulations.  Parts 9405 to 9430 are EAC regulations.  We should not include them in our eRegulations platform.   

@amykort

**Comment by porta-antiporta** [comment]
https://trello.com/c/bLKSh4ZH/27-fec-eregs-parts-9405-to-9430-chapter-ii-election-assistance-commission

**Comment by PaulClark2** [comment]
Same comment from Policy:  Nothing after Part 9039 is ours, so if those provisions are going to be included, the Commission can't take responsibility for their accuracy, updates, etc.

**Comment by porta-antiporta** [comment]
Will demo in latest version.
