### ISSUE TITLE
Regulations part 6 is missing from staging.

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#120]
https://fec-eregs.apps.cloud.gov/regulations/6 displays part 6.  

The TOC on [beta.fec staging](https://fec-stage-proxy.18f.gov/regulations) is missing part 6.  

Going to https://fec-stage-proxy.18f.gov/regulations/6 results in a 404.

We should be displaying part 6 on beta's staging.

Create (dig up) a canonical list of what the FEC regulations is.

**Comment by annalee** [comment]
@adborden and I got it back :).
