### ISSUE TITLE
Make the eRegs sub-header sticky

### ISSUE THREAD

**Issue by adborden** [18F/fec-eregs#124]
The FEC header is quite a bit larger than the eRegs header. Because the eRegs header is fixed, the header ends up consuming a lot of screen real estate. Instead, the header should be positioned static, and scroll with the page with the sub-header becoming fixed at the top of the viewport aka "sticky". The branding and site nav would scroll off canvas, but the dark blue breadcrumb would affix, along with the left and right rail.

Here's [a prototype demonstrating the behavior](https://adborden.github.io/eregs-scroll-prototype/). Note the behavior of the header, sub-header, left nav, and right sidebar at desktop and mobile screen sizes.

**Comment by adborden** [comment]
`fec-style` also implements [a sticky bar](https://github.com/18F/fec-style/blob/master/js/sticky-bar.js) which would need to be augmented to work for the eregs case.

**Comment by porta-antiporta** [comment]
@adborden I believe you had addressed this one already?

**Comment by adborden** [comment]
No, this work hasn't been done. However, since the issue was last created, the size of the FEC header design shrunk a bit, so the header doesn't take up as much space as it used to. Here's a screenshot of the current size on an iphone4 (simulated).
<img alt="screenshot from 2016-08-09 10-34-36" src="https://cloud.githubusercontent.com/assets/509703/17526668/160ec102-5e1d-11e6-9a3b-9afbc22237d6.png" width="320">
