### ISSUE TITLE
Secure ATO for Regulations

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#125]
Need to get ATO for releasing regulations to the public.  There is an [infrastructure issue](https://github.com/18F/Infrastructure/issues/643) open; but have this in our rep to track and provide updates.

Questions:
* What do we need for an ATO
* How much can we leverage betaFEC's ATO

**Comment by porta-antiporta** [comment]
Based off discussion on:
- the referenced [infrastructure issue](https://github.com/18F/Infrastructure/issues/643)
- discussion on 6/8 in #fec-legal

I've updated the beta.fec system diagram with the impacts legal resources has.
The *current* system is:
![production](https://cloud.githubusercontent.com/assets/16668007/15917878/6589b05c-2dc6-11e6-97d5-283c8df5817c.png)


The *updated* system is:
![production](https://cloud.githubusercontent.com/assets/16668007/15917895/854dd5ee-2dc6-11e6-98b1-0cb367e2361f.png)

Items in yellow are things we are taking from the core eregs; there may have been changes to them but they were done in a manner consistent with keeping those components core.

Items in red are things legal created specific to the project.
- fec-eregs : FEC styling to make the eregs viewer consistent with beta.fec
- elastic search (legal) : repository for our the indices of our FEC legal resources search
- FEC credential : stores credentials so that eregs can update eregs rds

**Comment by porta-antiporta** [comment]
Assuming the updated diagram is predominantly accurate the following are missing items we would need to follow up and document for @NoahKunin for ATO
- [ ] Integrate for fec-eregs (similar to atf-eregs)
 - [ ] New Relic
 - [ ] Quantified Code
 - [ ] Gemnasium
- [ ] Reconcile how to demonstrate we are `pulling from a stable master`from the core eregs components (regulations-site, regulations-core, regulations-parser)
 - [ ] Can likely replicate what was done for atf-eregs, notice and comment.  (While their are active code changes on master, latest on master is not always deployed to production environments)
- [ ] Confirm that the New Relic monitoring with openFEC API will also capture any errors coming from the elastic search instance for legal resources.  If not, modify the integration such that it does

Anything else?  There may be others that come from infrastructure leads but above are known gaps.

**Comment by porta-antiporta** [comment]
Updated diagram after discussion with @anthonygarvan and @LindsayYoung.  Note some changes impacted the common (i.e. data as well) stuff.

![production](https://cloud.githubusercontent.com/assets/16668007/15935958/d4a0afbe-2e2e-11e6-8cfa-7a8a3dc1a040.png)

**Comment by porta-antiporta** [comment]
Created #131 as an epic to track all the stories required for ATO

**Comment by porta-antiporta** [comment]
#127 
#128 
#129 
#130

Above are stories tracking outstanding work to achieve ATO.

**Comment by NoahKunin** [comment]
Hm, wait a moment - why does the CMS need FEC's creds...?

**Comment by LindsayYoung** [comment]
it

**Comment by LindsayYoung** [comment]
It is the cf credential service that we use for passwords and other secrets, they are named fec_credentials in cloud foundry, but they are for the respective projects and not from the FEC agency.

**Comment by NoahKunin** [comment]
Ok - so if I'm grok-ing correctly, it shouldn't read `FEC` it should read `beta.fec.gov` to clarify whose creds they are, right?

The presumption otherwise in the diagram and docs is that `FEC` means "the agency".

**Comment by LindsayYoung** [comment]
That makes sense. I am thinking since the space is small we could just say "cred service" to avoid the confusion. Though we can write it out if you think it is a necessary detail.

**Comment by adborden** [comment]
+1 to naming it "cred service", though I would suggest "secrets service" since they are not technically all credentials, but they are all sensitive that should be treated as secret.

**Comment by NoahKunin** [comment]
Feel free to embiggen as much as you need to give yourselves room for
labels or anything. I don't mind scanning and zooming around a big diagram
(and I have a huge external monitor in my office now for just this purpose!)

Thanks!!

On Thu, Jun 9, 2016 at 3:03 PM, Aaron D Borden <notifications@github.com>
wrote:

> +1 to naming it "cred service", though I would suggest "secrets service"
> since they are not technically all credentials, but they are all sensitive
> that should be treated as secret.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/fec-eregs/issues/125#issuecomment-225040551>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAifT2RjP6SiSp1Agq9pyPg3LmRWsPTYks5qKI2egaJpZM4IxGnl>
> .
>



-- 
Noah Kunin
18F Infrastructure Director | @18F <https://twitter.com/18F>

**Comment by porta-antiporta** [comment]
![production](https://cloud.githubusercontent.com/assets/16668007/15953492/0e868d72-2e91-11e6-84d7-4298ae0101a2.png)
