### ISSUE TITLE
Intermittent connection when searching

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#132]
When triggering a search we often get a connection error that forces the user to reload the page to get results.  This is a poor user experience, we need to address the connection error.

<img width="1052" alt="screen shot 2016-06-09 at 1 13 54 pm" src="https://cloud.githubusercontent.com/assets/16668007/15941010/140beb9a-2e44-11e6-93a5-c7a89ae541e1.png">

**Comment by porta-antiporta** [comment]
Sizing is based on the workaround of triggering a retry if the API returns a connection error.

**Comment by adborden** [comment]
Here's an app that can reproduce the issue. https://gist.github.com/adborden/f9a657bcd6b594db09b45cbac4fd2ee7
Which you can deploy with something like:

    $ cf push adborden-test -u none --no-route -b python_buildpack -i 1 -c "python idle.py"

@LindsayYoung and I looked into this and determined it is only affecting `dev` and `stage`. Here's the running theory:

Something closes idle connections after 20 minutes. I have confirmed that something in the cloud.gov stack times out idle connections. Locally I receive a connection FIN. On the subsequent connection, `urllib3` detects the connection is dropped, and re-establishes it before sending the requst :+1:. I'm not sure what is happening in `dev` at the TCP level, but the `urllib3` does not detect the connection was dropped and the next request fails.

In `prod` we see log lines like `INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection` so we know connections are being re-established in `prod`. We don't see these log lines in `dev` or `stage`. The suspicion is that the FIN is received on `prod`, but is not being received properly in `dev` or `stage`.

The `prod` API is behind API umbrella via `api.data.gov`, so the difference in routing might account for the difference we see in the different environments.

Knowing what is timing out the connections might give some clues here. The ELB fronting cloud.gov has a timeout. The CF gorouter has a timeout. `fec-proxy` has a timeout. None of these appear to be set to 20 minutes from what I can tell.

cc @dlapiduz
