### ISSUE TITLE
On mobile (or smaller screens) the table of contents is collapsed by default.

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#134]
When browsing eregs and going to a regulation, the table of contents is collapsed by default when the window is not maximized.

This causes an issue because when navigating to a regulation from the legal resources landing page, the user is shown a blank screen (as they need to click on a section to see content).  The control to expand the table of contents (**>**) doesn't stand out as the next interaction the user should make.

![screen shot 2016-06-13 at 11 14 03 am](https://cloud.githubusercontent.com/assets/16668007/16014719/0d93980a-3158-11e6-8ad5-b139c8c92562.png)

Instead the table of contents should be expanded by default

![screen shot 2016-06-13 at 11 14 16 am](https://cloud.githubusercontent.com/assets/16668007/16014727/1cba6caa-3158-11e6-90f0-30e75a90f36d.png)

**Implementation Note**
As discussed during standup, the root cause of the issue is that the table of contents is collapsed by default when the screen is not maximized for desktop.  That threshold level should be made smaller so that it is not collapsed when viewing from a mobile.

**Comment by adborden** [comment]
Just to clarify, the story is have the TOC open by default on all screens, right? Whether there is content or not?

Just going to throw this out there, the landing page for a reg is customizable. ATF has content per reg https://atf-eregs.apps.cloud.gov/478 with additional call to actions. We don't have to have custom content per reg for now, but maybe putting some custom content there would be helpful.

**Comment by porta-antiporta** [comment]
@adborden That's correct.  The TOC _should_ have content at all times in the viewer.

As far as customizing the landing page for a reg, we can do that at a later time. (Unlike ATF, FEC has a ton of regs so wouldn't be able to generate the content in time for each reg).

**Comment by cmc333333** [comment]
Something to note here: you don't need custom content per reg; it's definitely possible to have boiler plate that's shared by all of the regs.

**Comment by adborden** [comment]
Thanks @cmc333333 is it right that it's as simple as adding content to the `reg_main_content` block? https://github.com/adborden/regulations-site/blob/ebf6c318d2ff6a6d82e999ab518b4fd0be5a8275/regulations/templates/regulations/generic_landing.html#L18

If that's the case, it's fairly straight forward to add content, assuming we have content to add. However, there's some cost to bring in some of our content components from betaFEC, for example some of the content cues you see on https://beta.fec.gov/registration-and-reporting/. Keeping it simpler, the better, at least for now.

**Comment by cmc333333** [comment]
@adborden sounds right, yep. I understand the potential costs -- I'm trying to weight them against the additional costs that maintaining this type of flag entails :)

**Comment by porta-antiporta** [comment]
So I see two proposals:

1. Generate boilerplate info that can be shared across eregs
2. Proposal (for long term) around https://github.com/eregs/regulations-site/pull/448

Given we merged the above PR as a short term solution, I think that buys us time to create that generic information.  If the proposal in the above PR for a configurable setting is only being viewed as beneficial to `fec-eregs` may not make sense to implement and just rely on the generic regs information as the long term fix.
