### ISSUE TITLE
Navigation to a specific regulation

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#14]
Is there a way to pull up a specific reg by going straight to it (instead of by clicking through the TOC)

**Comment by porta-antiporta** [comment]
@PaulClark2 you can go to a specific part by entering the part number directly at the end of the URL.  fec-eregs.apps.cloud.gov/<part number>.

But were you asking for a mechanism in the UI itself where a user is already in a particular section in the reader as below?

<img width="1106" alt="screen shot 2016-03-08 at 1 52 59 pm" src="https://cloud.githubusercontent.com/assets/16668007/13614271/537e211a-e535-11e5-9d1d-642755875227.png">

**Comment by PaulClark2** [comment]
Yes, Policy is asking for the ability to use the UI to navigate to a different part.  I'm guessing manually changing the URL as a normal part of the process is a non-starter.  @amykort

**Comment by AmyKort** [comment]
I think they might have been looking for something like a TOC that lists everything (not just all of the parts) or an index, so it would be fewer clicks and less scrolling to get to the specific regulation you wanted, whether you were starting at the beginning or whether you were already browsing in a particular section. I don't think it is going to be an acceptable solution to manually change the URL.

**Comment by porta-antiporta** [comment]
With breadcrumbs in the legal resources section, the user can now easily access the TOC.
