### ISSUE TITLE
Navigation - Table of contents

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#15]
The box in the upper left that takes you back to the overall TOC isn't very intuitive.

**Comment by porta-antiporta** [comment]
Yes; the current design is very part specific.  Are FEC's regulations cross referencing each other's part a lot?  We would need to look at how we can make it more accessible.

**Comment by PaulClark2** [comment]
@amykort  I think there is a fair amount of cross-referencing across parts of our regs.

**Comment by AmyKort** [comment]
I think there are a lot of situations where you have to pull regulations from different parts to get the full picture of the law governing the activity you are looking at.

**Comment by porta-antiporta** [comment]
beta.fec.gov now has breadcrumbs that will let you easily get back to the regulations TOC. 
Mind if we close this issue?

<img width="299" alt="screen shot 2016-07-26 at 3 11 29 pm" src="https://cloud.githubusercontent.com/assets/16668007/17153695/69edbd80-5343-11e6-9078-1de1f42692c2.png">

**Comment by AmyKort** [comment]
Sounds good. Thank you!
