### ISSUE TITLE
Design content for Statutes Landing Page

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#155]
Statutes Landing page in the [current mockup](https://invis.io/AR7U3Y662) is only a placeholder.  

In order to correctly design it, need to understand the content that should be there such as:

- [ ] Intro
- [ ] Link to uscode version
- [ ] Link to FEC version
- [ ] Mapping of old to new statutes
- [ ] What else on fec.gov should be on the new landing page?

**Comment by porta-antiporta** [comment]
Also look at the [Enforcement landing page](https://gsa.invisionapp.com/share/AR7U3Y662#/screens/167711270) as a good starting point for different page elements that may apply to the statutes landing page

**Comment by jenniferthibault** [comment]
@jeanninehunter , here is a direct link to the Statutes page in that InVision mockup: https://gsa.invisionapp.com/share/AR7U3Y662#/screens/171040670

And here is what exists as a sort-of-not-quite-equivalent to that page on the current fec.gov 
http://www.fec.gov/law/feca/feca.shtml

**Comment by emileighoutlaw** [comment]
Statutes content being tracked here: https://github.com/18F/fec-eregs/issues/199

**Comment by emileighoutlaw** [comment]
Closing in favor of https://github.com/18F/fec-eregs/issues/199, so we can track all statutes content in a single issue. h/t to @porta-antiporta
