### ISSUE TITLE
Question:  Updates and changes

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#16]
How does it get updated? E.g., if we modify a reg, how do the new text and history get into the e-regs site?

**Comment by porta-antiporta** [comment]
@PaulClark2 Currently this would need to be a manual update if a new reg were published.  Also please note that per the discussions during the workshop, we were going to scope down the eregs viewer to only display the latest annual edition (for this first phase).  Main drivers was a) wrapping up the eregs viewer so team can look at search/navigation/linking and b) some of the federal register entries for historical information is missing.
