### ISSUE TITLE
eRegs collapsed panel shows portion of TOC

### ISSUE THREAD

**Issue by adborden** [18F/fec-eregs#161]
When the eRegs panel is collapsed, the TOC is still visible.
<img width="338" alt="screen shot 2016-07-05 at 9 45 28 am" src="https://cloud.githubusercontent.com/assets/509703/16592396/5b0de3e4-4295-11e6-98fb-74bc4f01606c.png">

You can see the borders of the TOC items in the collapsed panel.

**Comment by porta-antiporta** [comment]
hmmm... not seeing that behavior @adborden are u in dev / staging (i checked dev)

**Comment by adborden** [comment]
Shame on me for forgetting a URL https://fec-stage-proxy.18f.gov/regulations/111-3/2016-annual-111#111-3

Interesting, that it doesn't occur on every part. I just checked part 4, and did not see the issue.

**Comment by adborden** [comment]
De-prioritizing this because it only affects a few number regs. 111 is the only one I can find.

**Comment by porta-antiporta** [comment]
`juice isn't worth the squeeze` for this particular issue.  Closing.  Can reopen if feedback is submitted from the public pointing this one out.
