### ISSUE TITLE
hide help tips for unused features

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#164]
In the Regs interface, there is the help box in the right right (desktop). We should hide the tips for Table of Contents, Regulation timeline, Search since these refer to the tabs we are not using in the TOC column.

![image](https://cloud.githubusercontent.com/assets/2654503/16655066/b22a894c-4426-11e6-9529-bbd1f629d5b6.png)

**Comment by porta-antiporta** [comment]
How modular are the different sections within eRegs.  i.e. If we have a setting that controls whether we are supporting Regulation timeline and what not, we should have that also control the respective help sections.
