### ISSUE TITLE
Alert on Legal Resources landing has broken link

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#165]
The alert on the Legal landing page has a link to sign up to test features, but it's not working. It's just an anchor which needs to be replaced.

![image](https://cloud.githubusercontent.com/assets/2654503/16655193/382e8f52-4427-11e6-9b48-f9b184622d5e.png)

Correct URL: https://ethn.io/70862

**Comment by porta-antiporta** [comment]
solved by https://github.com/18F/fec-cms/pull/382
