### ISSUE TITLE
Remove Section-by-section analysis

### ISSUE THREAD

**Issue by cmc333333** [18F/fec-eregs#167]
This feature's relatively specific to CFPB regs, so you probably don't want that.

To deactivate, you can do something like https://github.com/18F/atf-eregs/blob/master/atf_eregs/settings/base.py#L21

**Comment by porta-antiporta** [comment]
Thanks @cmc333333. 

Does CFPB (or other eregs) support pulling FR content regarding "Explanation and Justifications"?   

An example [here](http://www.fec.gov/law/cfr/ej_compilation/2006/notice_2006-8.pdf#page=19) (search for `Explanation and Justification` to go to the start of the content.

**Comment by cmc333333** [comment]
That'd be a very similar concept to SxS, yep, but the SxS parser's not going to be able to pull those out. As we've discovered, each agency has it's own way of referencing the CFR within the preamble of final and proposed rules. Some are very explicit like CFPB and (perhaps) FEC in saying "these sections are related to these CFR sections/paragraph", while others weave the CFR references throughout a different structure.

In any case, you'd need to add back a step to parsing that pulls in Federal Register notices (which you are currently skipping to load only the latest annual editions).

**Comment by porta-antiporta** [comment]
👍

**Comment by porta-antiporta** [comment]
@cmc333333 

So if I am following correctly, `SIDEBARS` overrides regulations-site's default content on the right sidebar (Section by Section and Help).

i.e. To hide section by section analysis all we need to do is add the following:

```
SIDEBARS = (
    'regulations.generator.sidebar.help.Help',
)
```

**Comment by porta-antiporta** [comment]
cc:ing @tadhg-ohiggins as CM is out on vacation this week.  Any guidance/thoughts ^^?

**Comment by cmc333333** [comment]
@porta-antiporta you got it. You can also use it to re-order sidebar content, if you want
