### ISSUE TITLE
Navigation:  Index

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#17]
Would it be useful to include the 11 CFR Index to the e-regs (by link or otherwise) - some people are more comfortable with that than with coming up with specific search terms. Suggest having Ed's 18F UX team discover user thoughts on the issue.

**Comment by porta-antiporta** [comment]
@PaulClark2 Is this related to #14 and #15?  In summary, the current eregs viewer doesn't provide a very friendly mechanism to jump from part to part within the UI.  The user has to click on "eRegulations" on the upper left to get to an overall index/TOC of title 11.  Would want something more intuitive to the user once they are viewing a specific regulation/part.

**Comment by porta-antiporta** [comment]
This has been addressed via:

- Breadcrumbs in legal resources section that quickly takes you to an index.
- Prioritized search by a specific section number makes that the first hit in the list of results.
