### ISSUE TITLE
Modify title tag naming convention for regulations

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#173]
I noticed that the title for our regulations retains the eRegulations convention, which is:

`11 CFR § 100.2 | eRegulations`

We should remove the eRegulations branding as it's not important to our users. Instead we should replace "eRegulations" with **beta.FEC.gov** or **FEC**. I've asked about which is preferred in https://github.com/18F/fec-cms/issues/385. 

Additionally, we don't include the section description in the title, which I think we should. Cornell includes this as well as the other coding reference, which does seem to be part of the description:

![image](https://cloud.githubusercontent.com/assets/2654503/16777804/1029f7b0-4839-11e6-82ba-448734065c9d.png)

Assuming it's not much work, I think this is what the title should be:

`11 CFR § 100.14 State Committee, subordinate committee, district, or local committee (52 U.S.C. 30101(15)) | FEC`

Google will truncate this and seems to truncate after full words now. I'm not aware of any SEO penalty for long titles, but there could be. Also, they seem to occasionally append the source onto the link...

![image](https://cloud.githubusercontent.com/assets/2654503/16778051/33871cdc-483a-11e6-8313-7ff4f87c0180.png)

...but I'm not sure of the logic or if there's a way to force this. I mostly see it for PDFs or videos. If we could force this so that our title would get truncated like this, I think it'd be ideal:

`11 CFR § 100.14 State Committee, subordinate... - FEC`

Further reading: https://moz.com/blog/title-tag-length-guidelines-2016-edition

cc @emileighoutlaw @porta-antiporta

**Comment by emileighoutlaw** [comment]
Hey legal friends! We've decided on `_Title title title | FEC_` as our page title convention. I was going to file a PR in this repo to fix that, but I can't figure out where the page title is hiding in here :/
