### ISSUE TITLE
Through visual styling, clarify that "About eRegulations" is about the platform, or tool

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-eregs#174]
When viewing https://beta.fec.gov/regulations/ , distinguishing "The FEC Regulations, viewed online" and "eRegulations, the tool" as two different things is a tough. Users are there for the FEC's regulations, and we are essentially presenting a citation for where the tool comes from and how some might use it for themselves. This is neat in the open gov space, but secondary, and I think would benefit from a visual styling that feels a bit more separate.

This can primarily be tackled through visual styling, but I'm sure will also benefit from some slight copy tweaks as we finesse the design.

![screen shot 2016-07-12 at 2 50 50 pm](https://cloud.githubusercontent.com/assets/11636908/16779433/3501d6be-4840-11e6-9e42-d6d293850d26.png)

Styling of the "About eRegulations" page is a task of itself. The goal in this issue is to create thematic visual and conceptual separation. 

**Steps to completion:**
- Visual styling: @jenniferthibault
- Propose copy changes & review with @jeanninehunter

**Comment by porta-antiporta** [comment]
I'll also add understand whether we should keep the hyperlink to `Learn more about eRegulations' features`.

1. Look at our analytics and see who actually accesses that link
2. The content of that link contains features we don't support.

**Comment by jenniferthibault** [comment]
2!!!! I was confused. Thanks for confirming.
