### ISSUE TITLE
Support Key Phrase Searching

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#192]
see #188 for background.

We need to support key phrase searching for Regulations, AOs (all sources).

Following the Google notation, we will use `" "` to specify a key phrase to be searched.  A key phrase means that we are searching for _ALL_ the terms in the phrase.

To be discussed in grooming:
- Should a key phrase be an exact match?
- Should a key phrase be a shorter proximity search.  For example `travel reimbursement` gets hits for `reimbursement of travel` etc

For this story:

- [ ] Search field takes in key phrases as bounded by `" "`
- [ ] Search field can take in key phrases and key words in the query
- [ ] Search field is updated across all pages
 - Notably, beta.fec.gov/regulations : Discuss in grooming whether this should be taken out as a separate story.
- [ ] Annotated help / context to do key phrase searching is in built out as specified in #94

**Comment by adborden** [comment]
@anthonygarvan do you have any experience with ES's [Simple Query String Query](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-simple-query-string-query.html)? It sounds like it's meant for this usecase, where we have special syntax for various full-text features. It would save us from having to write our own parsing and query logic. Downside is that it looks less tunable.

**Comment by porta-antiporta** [comment]
https://github.com/18F/openFEC/pull/1898
