### ISSUE TITLE
Implement Citations Bar on AO Canonical Page

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#193]
See #95 

Citations on the AO Canonical page should include:
- Regulations cited by the final opinion (ignore other documents)
- AOs cited by the final opinion (ignore other documents)

Canonical AO page is [here](https://gsa.invisionapp.com/d/main#/console/7833288/167711253/preview)

This is dependent on #71

**Comment by jenniferthibault** [comment]
Tagging @emileighoutlaw for content strategy on the sidebar template.

**Comment by emileighoutlaw** [comment]
Is this still relevant? cc @jenniferthibault

**Comment by jenniferthibault** [comment]
Yyyyyes. But I don't remember why it's a content strategy question, it may have been related to the formatting of citation links, availability of helper text for those citations (the italicized topics listed in Reg & Reporting content) or the title of the resources side bar. _(Kicks past self for not giving good context in GitHub comments)_ Each of these have been areas we've been paying high-level attention to in the sidebars.

Sorry for the InVision hotspot overlay
<img width="256" alt="screen shot 2016-11-01 at 5 23 54 pm" src="https://cloud.githubusercontent.com/assets/11636908/19908084/0a3b8162-a058-11e6-9373-5a3944d47724.png">


So far we have the designs for these, but they haven't been implemented, it's just placeholder `Coming soon.`
https://beta.fec.gov/data/legal/advisory-opinions/2012-38/

**Comment by porta-antiporta** [comment]
If I may interject with the context.

@jenniferthibault that is exactly the question.  When we first designed the AO canonical page, we didn't really have an established pattern on how to call them out.  So we punted.

When we implemented MUR citations, we leveraged the pattern from the registration and reporting sections.  So I think the content strategy question was to confirm (and update the design) to reflect that pattern.

**Comment by emileighoutlaw** [comment]
No worries! This is totally my fault for leaving this comment-less for 25 days :upside_down_face: 

I think the decided-upon content strategy for legal citations is:

> ### Legal citations 
> Relevant to this page:

> **Regulations**
> 11 CFR XXXX
> _Title_

> **Statutes**
> 52 USC XXXXXX
> _Title_

> **Advisory opinions**
> 2014-04 XXXX


So if the content strategy is clear, is this first a dev task (implementation) and then a content review task (for consistency with other sections of the website?)

**Comment by jenniferthibault** [comment]
I think yes. @adrianwebb this could be a possible candidate for dev grooming for the next sprint?

**Comment by adrianwebb** [comment]
Awesome, that sounds good to me.  Thanks @jenniferthibault !

**Comment by noahmanger** [comment]
I missed this earlier. Is there anything else we need to do with this?

**Comment by jenniferthibault** [comment]
I just edited @emileighoutlaw's comment above to reflect the latest citation format.
From the design perspective, it's a complete story ready for implementation.

**Comment by emileighoutlaw** [comment]
Agreed. Thanks to Jen for updating the citation format. I also added Federal Register notices, just in case those come up in these citations.

I believe this is a dev implementation task? But I'm happy to consult/collaborate, if I can be helpful.

**Comment by noahmanger** [comment]
I broke these out into smaller issues, so closing.

**Comment by jenniferthibault** [comment]
Last little bit of dot-connecting, the references for other AOs cited in this AO is being tracked in https://github.com/18F/openFEC/issues/2124
