### ISSUE TITLE
Write statutes content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-eregs#199]
This issue is for tracking our statutes content. We'll need content for:

- Legal landing page (https://beta.fec.gov/legal-resources/)
- Statutes subpage (https://beta.fec.gov/legal-resources/statutes/)

We have a statutes landing page [mockup](https://invis.io/AR7U3Y662), which is only a placeholder. In keeping with advisory opinions and regulations, I think something clear lightweight is the best approach for this content. 

# Legal landing page
Proposed blurb:
> ### Statutes
The acts of Congress that shape campaign finance law are the Federal Election Campaign Act, the Presidential Election Campaign Fund Act and the Presidential Primary Matching Payment Account Act. Those acts are collected and restated as law in Title 26 and Title 52 of the U.S. Code (USC). 

> This archive contains the portions of 26 USC and 52 USC that are administered by FEC. 

> [ [Explore statutes]() ]

# Statutes subpage
Things to think about and include (draft coming soon):
- [x] Intro
- [x] Link to uscode version
- [x] Link to FEC version
- [ ] Mapping of old to new statutes -- Decided to be in a later release
- [x] What else on fec.gov should be on the new landing page?

Proposed blurb:

> ## Statutes
The FEC administers and enforces the Federal Election Campaign Act, the Presidential Election Campaign Fund Act and the Presidential Primary Matching Payment Account Act. Those acts and amendments, which are passed by Congress and signed by the President, are collected and restated as law in Title 52 and Title 26 of the U.S. Code.

> ## Full text of statutes
Specifically, the FEC interprets enforces the statutes found in Title 52, Subtitle III and Title 26, Subtitle H. There are two options for accessing these statutes:

> 1. Access the FEC’s compilation of statutes. That PDF contains Title 52, Subtitle III, Title 26, Subtitle H and additional provisions of the U.S. Code that aren’t enforced by FEC but are relevant to people involved in federal elections.
> 2. Access the Government Printing Office (GPO) version of Title 52, Subtitle III and Title 26, Subtitle H.

![statutes landing copy 2](https://cloud.githubusercontent.com/assets/11636908/17983811/7826aba4-6adc-11e6-9a10-da5fb575a3a5.png)

Thanks! 🌺

**Comment by AmyKort** [comment]
How about this? 

Statutes
The FEC administers and enforces the Federal Election Campaign Act, the Presidential Election Campaign Fund Act and the Presidential Primary Matching Payment Account Act. Those acts are collected and restated as law in Title 26 and Title 52 of the U.S. Code (USC). 
This archive contains the portions of 26 USC and 52 USC that are administered by FEC.

**Comment by emileighoutlaw** [comment]
Sure thing! Is there a reason we don't want to say that acts come from Congress? Curious to know as I dive into more legal work. :)

**Comment by AmyKort** [comment]
No. I just thought this was shorter. I also wondered if it introduced complexity when we weren't actually going to address that complexity--we're just providing the statute.

**Comment by emileighoutlaw** [comment]
Oh I see! One of the interesting things we've seen in talking to folks is that there's little understanding about what the difference is between statutes and regulations. I was hoping that by making it clear statutes come out of Acts which come out of Congress, it would help clarify a really complicated government thing. But maybe there's a better way to get at this. Any ideas?

**Comment by emileighoutlaw** [comment]
I also admit that lawyers probably don't struggle with this distinction. But I'd love it if the barrier to entry wasn't lawyer level for this

**Comment by AmyKort** [comment]
Statutes
The FEC administers and enforces the Federal Election Campaign Act, the Presidential Election Campaign Fund Act and the Presidential Primary Matching Payment Account Act. Those acts and amendments, which are passed by Congress and signed by the President, are collected and restated as law in Title 26 and Title 52 of the U.S. Code (USC).
This archive contains the portions of 26 USC and 52 USC that are administered by FEC.

**Comment by emileighoutlaw** [comment]
I love it! You are a word wizard, Amy! 🎩 🐇

**Comment by jenniferthibault** [comment]
@emileighoutlaw I plunked that all in on the Legal Resources landing page. Is it on track, or did you have anything else in mind?

![legal resources home](https://cloud.githubusercontent.com/assets/11636908/17898718/cccdcb4a-6926-11e6-99d6-478965a8f22a.png)

**Comment by jenniferthibault** [comment]
I just updated the image above because I realized it had old placeholder content in it for the regs & advisory opinion sections. Fixed with the live text!

**Comment by emileighoutlaw** [comment]
That content looks good so far. I'd like to get a paragraph in about why folks might use the FEC version vs. US Code version. Working on that now, but it'll be an additional paragraph on the statutes subpage, not this landing page.

**Comment by AmyKort** [comment]
By FEC version, do you mean the book version of the statute?

**Comment by porta-antiporta** [comment]
@AmyKort yes the ORANGE book :trollface:  
http://www.fec.gov/law/feca/feca.shtml lists the 2 docs.  Would like to add when folks might want to use one vs. the other.

**Comment by AmyKort** [comment]
Hahaha. Got it.

**Comment by porta-antiporta** [comment]
Also, should there be a `the` in the following statement:

"This archive contains the portions of 26 USC and 52 USC that are administered by **the** FEC."

**Comment by AmyKort** [comment]
On "Coming Soon: Enforcement matters" it says "coming soon" twice. Should the second one in front of the link to the old site be deleted?

**Comment by emileighoutlaw** [comment]
Oh good catch! Yes, I think so, @AmyKort! (And yes to adding that `the`, Porta)

I think this is good for the introductory text. I'd like do a careful, copyediting review this intro in the HTML before we launch @jenniferthibault and @porta-antiporta . I'm also trying to finish up that second paragraph for https://github.com/18F/fec-eregs/issues/208#issuecomment-241752072.  

But we are very close!

**Comment by emileighoutlaw** [comment]
Here's a whack at the statutes landing page text. It took me a long time to grok this, and I'm still not sure I completely understand, so I'm looking to @amykort to help me make this better!

> ## Statutes
The FEC administers and enforces the Federal Election Campaign Act, the Presidential Election Campaign Fund Act and the Presidential Primary Matching Payment Account Act. Those acts and amendments, which are passed by Congress and signed by the President, are collected and restated as law in Title 26 and Title 52 of the U.S. Code (USC).

> ## Full text of statutes
>  Title 26 and Title 52 each contain many different statutes. Those statutes were enacted separately, over time and organized into titles by editors of the U.S. Code. This archive contains the portions of 26 USC and 52 USC that are administered by FEC. 

Visit the [U.S. Code website]()(uscode.house.gov) to see how these titles have changed over time and to see a more comprehensive breakdown of the statutes contained in each title.

**Comment by AmyKort** [comment]
I'm already confused. I thought we were making the distinction between the section-by-section compilation of the laws administered by the FEC (which is what we're adding to the search) and the pdf version of the Federal Campaign Finance laws compiled by the FEC. That publication also includes as an appendix the text of additional provisions of the United States Code, which are not in the Federal Election Campaign Act, but may be relevant to persons involved in federal elections. Those provisions include: 
•	Sections of the tax code administered by the Internal Revenue Service that govern tax-exempt 501(c) groups and so-called 527 organizations (additional provisions of 26 U.S.C. also apply);
•	Laws administered by the Federal Communications Commission that govern broadcast communications; and
•	Criminal provisions administered by the Department of Justice that relate to elections and political activity.
We encourage folks to contact the agencies listed above for additional information on the laws they administer.

**Comment by AmyKort** [comment]
I'd thought the first iteration of this feature would not provide the ability to browse through the statute. I thought we were providing statutory search results through the integrated search first, and then coming back later to add the ability to browse. Is that correct? In that case, the only way to browse through the campaign finance laws is still going to be the via the pdf.

**Comment by emileighoutlaw** [comment]
I'm sure this is my misunderstanding and not yours since I hopped into the statutes section midway through development. We don't need anything other than what's copied below and pre-approved for this release, but I'm going to put a time on our calendar to talk through this so *I* understand it better. 


> ## Statutes

> The FEC administers and enforces the Federal Election Campaign Act, the Presidential Election Campaign Fund Act and the Presidential Primary Matching Payment Account Act. Those acts and amendments, which are passed by Congress and signed by the President, are collected and restated as law in Title 26 and Title 52 of the U.S. Code (USC).

**Comment by AmyKort** [comment]
Sounds great--except our history together suggests that I'm usually the one who is mistaken.

**Comment by porta-antiporta** [comment]
@AmyKort You are correct, we wouldn't be providing an ability to browse the statutes the same way we can currently browse the 11 CFR in this first release.  We are:
* Adding statutes (as written by GPO/US Code) in the universal search.  When a user clicks on a link to a search result, it will take them to the appropriate section of the statute on GPO.
* Adding a landing page ([invision mockup](https://gsa.invisionapp.com/share/AR7U3Y662#/171040670_Statutes_Landing_Page)) to provide an overview of statutes.  This page is akin to the following page on [fec.gov](http://www.fec.gov/law/feca/feca.shtml) 

So similarly we were thinking to provide a link to the full statute of *both* the FEC compilation of the FECA (the [pdf](http://www.fec.gov/law/feca/feca.pdf) of the gray book) and a link to GPO/USC's [pdf](https://www.gpo.gov/fdsys/pkg/USCODE-2014-title52/pdf/USCODE-2014-title52.pdf) .  So @emileighoutlaw's question is if someone wanted to gain access to the full statute; when might they want to refer to the FEC compilation vs. GPO.

This snippet seems to be one of the reasons to go to FEC's compilation.

> That publication also includes as an appendix the text of additional provisions of the United States Code, which are not in the Federal Election Campaign Act, but may be relevant to persons involved in federal elections. Those provisions include: 
• Sections of the tax code administered by the Internal Revenue Service that govern tax-exempt 501(c) groups and so-called 527 organizations (additional provisions of 26 U.S.C. also apply);
• Laws administered by the Federal Communications Commission that govern broadcast communications; and
• Criminal provisions administered by the Department of Justice that relate to elections and political activity.

**Comment by porta-antiporta** [comment]
Also, please note that the remapping of the statute from 2 USC to 52 USC would be part of a later release (there are backend API changes needed to support such logic).

**Comment by emileighoutlaw** [comment]
Okay— famous last words here, but _I think_ I understand this now. Looking for 👀 from @AmyKort and @porta-antiporta 


> ## Statutes
The FEC administers and enforces the Federal Election Campaign Act, the Presidential Election Campaign Fund Act and the Presidential Primary Matching Payment Account Act. Those acts and amendments, which are passed by Congress and signed by the President, are collected and restated as law in Title 26 and Title 52 of the U.S. Code.

> ## Full text of statutes
Specifically, the FEC enforces the statutes found in Title 26, Subtitle H and Title 52, Subtitle III. There are two options for accessing these statutes:

> 1. Access the FEC’s [PDF compilation]() of statutes. The PDF contains Title 26, Subtitle H, Title 52, Subtitle III and additional provisions of the U.S. Code that aren’t enforced by FEC but are relevant to people involved in federal elections.
> 2. Access the Government Printing Office’s PDF version of [Title 52, Subtitle III]() and [Title 26, Subtitle H]().

**Comment by porta-antiporta** [comment]
Design question for @jenniferthibault: should these be links or a download button similar to the download button for `Final opinion` on the AO canonical page?

**Comment by AmyKort** [comment]
The text looks great to us with two small changes:

In the first sentence, I would say "interprets and enforces" rather than just "enforces."

I would put the Title 52 bits before the Title 26 bits, mainly because Title 52 is the bulk of what you think of as the campaign finance law.

**Comment by emileighoutlaw** [comment]
Can do, @AmyKort !! 

Re the buttons: One of the reasons I went with inline links is because I suspect we'd need fairly lengthy button copy. A lá

> ## Statutes
The FEC administers and enforces the Federal Election Campaign Act, the Presidential Election Campaign Fund Act and the Presidential Primary Matching Payment Account Act. Those acts and amendments, which are passed by Congress and signed by the President, are collected and restated as law in Title 52 and Title 26 of the U.S. Code.

> ## Full text of statutes
Specifically, the FEC interprets enforces the statutes found in Title 52, Subtitle III and Title 26, Subtitle H. There are two options for accessing these statutes:

> 1. Access the FEC’s compilation of statutes. That PDF contains Title 52, Subtitle III, Title 26, Subtitle H and additional provisions of the U.S. Code that aren’t enforced by FEC but are relevant to people involved in federal elections.
> 2. Access the Government Printing Office (GPO) version of Title 52, Subtitle III and Title 26, Subtitle H.

> [[FEC statutes (PDF)]()] [[Title 26, GPO (PDF)]()] [[Title 52, GPO (PDF)]()]


Those buttons are more confusing to scan than the inline links. But I do care about consistency. So If Jen thinks we should visually have buttons, I can work on this.

**Comment by porta-antiporta** [comment]
Links to the different PDFs

[FEC](http://www.fec.gov/law/feca/feca.pdf)
[GPO 52 USC Subtitle III](https://www.gpo.gov/fdsys/pkg/USCODE-2014-title52/pdf/USCODE-2014-title52-subtitleIII.pdf)
[GPO 26 USC Subtitle H](https://www.gpo.gov/fdsys/pkg/USCODE-2014-title26/pdf/USCODE-2014-title26-subtitleH.pdf)

**Comment by jenniferthibault** [comment]
Tinkered around a bit, and the approach that I think makes the best use of existing patterns, _and_ hints to what's about to happen is using a document preview image. We do this on the [registration and reporting pages](https://beta.fec.gov/registration-and-reporting/) with campaign guide PDFs, and this adapts that format for displaying multiple documents grouped with one paragraph.

![statutes landing copy 2](https://cloud.githubusercontent.com/assets/11636908/17983811/7826aba4-6adc-11e6-9a10-da5fb575a3a5.png)

The document screenshots aren't that exciting (and maybe in a future iteration I could think about a design for a template for these doc previews) but I do think it's really successful in:
- showing that it's a non-HTML page
- hinting that it's going to open something that doesn't feel exactly like the betaFEC site
- making the page more visual 
- creating a stronger call to action

It also seems to help by grouping each document with one of the two approaches, so that you can see easily how many docs there are (2 approaches, three docs, quick!)

A few details:
- Both the image and the text would link to the PDF
- It would be good if we could attach analytics event trackers to each of these documents to see what people are using.

**Comment by AmyKort** [comment]
I really like it!

**Comment by emileighoutlaw** [comment]
Me too! You're amazing, Jen :)

**Comment by porta-antiporta** [comment]
updated the issue description with the final copy and design for the statutes landing page
