### ISSUE TITLE
Presentation:  reserved sections

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#20]
Part 6: Because each individual section is separately labeled "reserved" (instead of grouped together), the Part is hard to navigate, and the TOC scrolling bar is so small that it disappears behind the TOC header.

**Comment by porta-antiporta** [comment]
https://trello.com/c/rrqA7AEd/39-when-a-regulation-has-several-contiguous-sections-that-are-reserved-i-e-section-6-the-ui-should-optimize-and-list-the-range-of-s

**Comment by porta-antiporta** [comment]
We kinda lost track of this after moving from Trello to Zenhub.  Adding to a sprint.

Sections 6.177-6.999 are all reserved, we should just have that range as a single item in the TOC of the eregs viewer.

![screen_shot_2016-03-08_at_2 37 04_pm](https://cloud.githubusercontent.com/assets/16668007/16665310/bd680420-4448-11e6-8b2f-70758149408c.png)

**Comment by vrajmohan** [comment]
Discussed this with @cmc333333. Rather than introducing new parsing flags, we agreed upon a simple heuristic - "only section spans that are <= 3 sections get expanded".

**Comment by vrajmohan** [comment]
This is fixed through https://github.com/eregs/regulations-site/pull/460 and https://github.com/eregs/regulations-parser/pull/300. It will be released when https://github.com/18F/fec-eregs/issues/238 is fixed.
