### ISSUE TITLE
"Opinion" is highlighted in hits when searching Advisory Opinions

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#206]
https://fec-dev-proxy.18f.gov/data/legal/search/?search_type=advisory_opinions&search=filing

When searching `Advisory opinions` the word `opinion` is always highlighted in search results (even though `opinion` was not in any of the search terms).

**Comment by adborden** [comment]
https://beta.fec.gov/data/legal/search/?search_type=regulations&search=201.4+commission+public+meeting

Looks like this is coming from our [query on the "Final Opinion" category](https://github.com/18F/openFEC/blob/b5f8454509d99393456bc92adeedc2aa50735069/webservices/resources/legal.py#L21), "final" is also highlighted.

**Comment by porta-antiporta** [comment]
no longer occurring after latest deploy.
