### ISSUE TITLE
Create Statutes Landing Page

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#208]
Implement landing page based off #155 and #199 
- [ ] Include test for links

> ## Statutes
The FEC administers and enforces the Federal Election Campaign Act, the Presidential Election Campaign Fund Act and the Presidential Primary Matching Payment Account Act. Those acts and amendments, which are passed by Congress and signed by the President, are collected and restated as law in Title 52 and Title 26 of the U.S. Code.

> ## Full text of statutes
Specifically, the FEC interprets enforces the statutes found in Title 52, Subtitle III and Title 26, Subtitle H. There are two options for accessing these statutes:

> 1. Access the FEC’s compilation of statutes. That PDF contains Title 52, Subtitle III, Title 26, Subtitle H and additional provisions of the U.S. Code that aren’t enforced by FEC but are relevant to people involved in federal elections.
> 2. Access the Government Printing Office (GPO) version of Title 52, Subtitle III and Title 26, Subtitle H.

![statutes landing copy 2](https://cloud.githubusercontent.com/assets/11636908/17983811/7826aba4-6adc-11e6-9a10-da5fb575a3a5.png)

**Comment by adborden** [comment]
When the feature flag is off, we should use the content "Coming soon.  Statutes are available on [FEC.gov](http://www.fec.gov/law/feca/feca.shtml#statutes)." as per https://github.com/18F/fec-cms/pull/442/files/49880fe725ab2759209443f61390c6a0df029886#r75557457

**Comment by jenniferthibault** [comment]
I got a small head start looking through the templates, and seems like the same one we used for the AO landing page could be a good first scaffolding to build on. This is totally totally dependent on the content that's coming, but wanted to give @emileighoutlaw a form to think about:

![statutes landing](https://cloud.githubusercontent.com/assets/11636908/17896099/556eb810-691d-11e6-9eea-0f3fa33d0213.png)

**Comment by porta-antiporta** [comment]
This is where we landed:

#  Content
> ## Statutes
The FEC administers and enforces the Federal Election Campaign Act, the Presidential Election Campaign Fund Act and the Presidential Primary Matching Payment Account Act. Those acts and amendments, which are passed by Congress and signed by the President, are collected and restated as law in Title 52 and Title 26 of the U.S. Code.

> ## Full text of statutes
Specifically, the FEC interprets enforces the statutes found in Title 52, Subtitle III and Title 26, Subtitle H. There are two options for accessing these statutes:

> 1. Access the FEC’s compilation of statutes. That PDF contains Title 52, Subtitle III, Title 26, Subtitle H and additional provisions of the U.S. Code that aren’t enforced by FEC but are relevant to people involved in federal elections.
> 2. Access the Government Printing Office (GPO) version of Title 52, Subtitle III and Title 26, Subtitle H.

#  Design

![statutes landing copy 2](https://cloud.githubusercontent.com/assets/11636908/17983811/7826aba4-6adc-11e6-9a10-da5fb575a3a5.png)
