### ISSUE TITLE
Links/definitions:  Some definitions inaccurate 

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#21]
Some of the linked definitions don't accurately reflect the term as used in context (e.g., in 1.1(b), "Act" is linked to the definition of FECA, even where the word is used in term "Privacy Act"; in 100.1, "Election" and "Commission" are individually linked even when used within the phrases "Federal Election Commission" and "Federal Election Campaign Act")

**Comment by porta-antiporta** [comment]
This is a duplicate of #10  When that's addressed, this one will be also.

**Comment by PaulClark2** [comment]
Moving the text above to #10 and closing this issue.
