### ISSUE TITLE
Implement Statutes Search Results page

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#210]
#207 and #209 implemented the API changes to return Statute search results.

This story will now implement the UI changes to support statutes

- [x] Update search field to include a `Statute` option
- [x] Searching across `All` should include searching across statutes
- [x] Implement Search result per the following [mockup](https://invis.io/AR7U3Y662#/171040672_Statutes_Search_Results)
- [x] Update universal search results to include Statutes
- [x] Include tests

**Comment by adborden** [comment]
We should be implementing some of the "new" patterns from https://github.com/18F/fec-style/issues/318. I'm not sure if [accordions](https://github.com/18F/fec-style/issues/318#issuecomment-220356244) are where we landed.
