### ISSUE TITLE
eregs on cloud foundry keeps going unresponsive

### ISSUE THREAD

**Issue by adborden** [18F/fec-eregs#214]
Usually this manifests as a very long response from fec-dev-proxy, ending with a 502. Looking at the logs, eregs itself is returning a 502 or a 504. I believe this is because cloud.gov restarts the ES cluster, or does some maintenance, but eregs just never tries to reconnect to ES, it just uses the old stale connection and continually times out.

**Comment by adborden** [comment]
Happened again this morning. Here's a log showing no output leading up to the outage, then on receiving the `cf restart` command, all the open connections are closed and result in 502. The proxy has already timed out and returned 504, but the point is that these instances seem to just stop being able to process requests and hang indefinitely. The instances don't appear to be overloaded, they look like they're doing nothing.

```
$ cf app eregs
     state     since                    cpu    memory           disk           details
#0   running   2016-08-23 06:44:36 AM   0.0%   76.8M of 512M    279.7M of 1G
#1   running   2016-08-23 06:44:36 AM   0.0%   157.5M of 512M   279.9M of 1G
```

https://logs.cloud.gov/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2016-08-30T18:00:19.000Z',mode:absolute,to:'2016-08-30T18:19:19.127Z'))&_a=(columns:!('@message',RTR.status,RTR.remote_addr,'@source.instance'),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:%5Blogs-app-%5DYYYY.MM.DD,key:'@source.space.name',negate:!f,value:prod),query:(match:('@source.space.name':(query:prod,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:%5Blogs-app-%5DYYYY.MM.DD,key:'@source.org.name',negate:!f,value:fec),query:(match:('@source.org.name':(query:fec,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:%5Blogs-app-%5DYYYY.MM.DD,key:'@source.app.name',negate:!f,value:eregs),query:(match:('@source.app.name':(query:eregs,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:%5Blogs-app-%5DYYYY.MM.DD,key:'@source.name',negate:!t,value:METRIC%2F0),query:(match:('@source.name':(query:METRIC%2F0,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:%5Blogs-app-%5DYYYY.MM.DD,key:'@source.name',negate:!t,value:METRIC%2F1),query:(match:('@source.name':(query:METRIC%2F1,type:phrase))))),index:%5Blogs-app-%5DYYYY.MM.DD,interval:auto,query:(query_string:(analyze_wildcard:!t,query:'*')),sort:!('@timestamp',desc),vis:(aggs:!((params:(field:'@source.space.name',orderBy:'2',size:20),schema:segment,type:terms),(id:'2',schema:metric,type:count)),type:histogram))&indexPattern=%5Blogs-app-%5DYYYY.MM.DD&type=histogram

**Comment by adborden** [comment]
BTW, I’m actually leaning away from ES now, originally it seemed to be correlated with a ES-wide reboot on cloud.gov. I was thinking the connection was reset, but eregs failed to pick up on that. But looking into the docs, pyelasticsearch has a default timeout of 10s, so pyelasaticsearch should be able to handle that case. Also, we haven't seen any issues with our other ES connections.

After looping in #eregs, they mentioned having similar unexplained errors and switched to gunicorn. The issues resolved, but it's unclear if it was coincidence.

**Comment by porta-antiporta** [comment]
For now closing in favor of #250.  If after that story, this persists we can reopen.
