### ISSUE TITLE
Question: Links to U.S. Code?

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#22]
Is it possible to link USC cites?

**Comment by porta-antiporta** [comment]
@PaulClark2 Is there a particular location you had in mind to link the user to?  i.e. Is there a site that hosts a viewer for the U.S.C?

**Comment by PaulClark2** [comment]
I think the Policy folks that looked that were thinking it'd be nice to be able to view the USC from within the eRegulation viewer.  That was my take on their question.  @amykort is that your understanding, too?  

I'm unaware of a USC viewer.   @wluoFEC @amykort @amypike are any of you aware of a USC viewer?

**Comment by cmc333333** [comment]
@porta-antiporta consider [turning on](https://github.com/18F/atf-eregs/blob/master/atf_eregs/settings/base.py#L24) and extending the external citations parser. It [currently](https://github.com/18F/regulations-parser/blob/master/regparser/layer/external_types.py) links to FDSYS for certain CFR, USC, Public Law, and Statutes at Large citations.

**Comment by AmyKort** [comment]
The regulations link to the statutory citations, so if we could make those live that would be great.

**Comment by tadhg-ohiggins** [comment]
Since the U.S.C. links are working (see https://fec-eregs.apps.cloud.gov/100-1/2016-annual-100#100-1 for an example), any objections to my closing this issue?

**Comment by AmyKort** [comment]
That would be fine with me. Thanks!
