### ISSUE TITLE
Supplement Universal Search to Include Enforcement Matters / MURs - Archived MURs

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#225]
https://github.com/18F/fec-eregs/issues/220#issuecomment-242763838

<img width="713" alt="screen shot 2016-08-26 at 11 11 06 am" src="https://cloud.githubusercontent.com/assets/11636908/18010308/f0e52448-6b7d-11e6-9f9d-0d218447929b.png">

**Comment by porta-antiporta** [comment]
@adborden @jenniferthibault The FEC provided the names for the archived MUR cases https://github.com/18F/fec-eregs/issues/220#issuecomment-243451348.  The API will be returning these so we will be able to display them on the search results after all.  From the earlier mockup, the MUR name is `Republican National Committee`.  I think we could display that under the MUR case number and above the "Archived Case" icon.  Do you agree?


<img width="474" alt="screen shot 2016-08-30 at 9 13 18 am" src="https://cloud.githubusercontent.com/assets/16668007/18092481/09d49c88-6e92-11e6-8ef0-b764487ea777.png">

**Comment by jenniferthibault** [comment]
Yep! I included that design change on the mockups in https://github.com/18F/fec-eregs/issues/243#issuecomment-243917255

Question: I'd kept the column named the same `Case, Committee` , but would it make sense to just call that column `Name` now?

**Comment by porta-antiporta** [comment]
Naming it "name" makes sense to me. Especially because that's what it is referred to in current MURS as well

**Comment by jenniferthibault** [comment]
Great, mockups over in #243 updated with that change.
