### ISSUE TITLE
Implement Enforcement Matters Search Results page - Archived MURs

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#226]
https://github.com/18F/fec-eregs/issues/220#issuecomment-242763838

<img width="713" alt="screen shot 2016-08-26 at 11 11 06 am" src="https://cloud.githubusercontent.com/assets/11636908/18010308/f0e52448-6b7d-11e6-9f9d-0d218447929b.png">

**Comment by porta-antiporta** [comment]
cc: @jenniferthibault as we will have some design questions on this page given
- older mockup
- need to understand mobile given increased number of fields

**Comment by porta-antiporta** [comment]
See https://github.com/18F/fec-eregs/issues/225#issuecomment-243452915 re: availability of MUR Name.  Implementing #225 should make this pretty seamless for this story, assuming re-use.

**Comment by jenniferthibault** [comment]
@porta-antiporta what's the older mockup you're referencing?

**Comment by porta-antiporta** [comment]
one day @jenniferthibault i promise i'll remember to include links to things i reference in comments.  here's the old mockup. https://gsa.invisionapp.com/share/AR7U3Y662#/screens/167711268

**Comment by jenniferthibault** [comment]
@adborden / @anthonygarvan The design questions over in #243 have been wrapped up to a good point for the first iteration and this should be ready for implementation. 

I've updated the following with the layouts:
- [desktop InVision for search](https://gsa.invisionapp.com/share/S58HMFKMB#/185960388_Enforcement_-_Search)
- [mobile InVision for search](https://gsa.invisionapp.com/share/MA8ID5U6Z#/186537529_Enforcement_Search-Mobile)
