### ISSUE TITLE
Implement Archived MURs Canonical Page

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#227]
![mur-archived-canonical copy](https://cloud.githubusercontent.com/assets/11636908/18015071/0cd0b9ae-6b94-11e6-8965-3a2bbfc3178e.png)

- [x] Citations to statutes should open a new tab
- [ ] Citations to regulations should open eregs viewer in same tab

**Comment by porta-antiporta** [comment]
We will have MUR Name after all. https://github.com/18F/fec-eregs/issues/225#issuecomment-243452915.  So it should be displayed on the MUR Canonical page.

**Comment by adborden** [comment]
For the regulation citations, the API returns the GPO PDF url, so those links will open in a new tab. @porta-antiporta that is okay in the near term? Easy change to swap it back once API is returning eregs urls.
