### ISSUE TITLE
Content for MURs

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#233]
Need to develop content for:
1. `Enforcement Matters` section on Legal Resources Landing Page
    - [mockup](https://gsa.invisionapp.com/share/AR7U3Y662#/171042404_Legal_Resources_Home_Statutes)
2. `Enforcement Matters` Landing Page
    - [mockup](https://gsa.invisionapp.com/share/AR7U3Y662#/screens/167711270)
    - Intro blurb to Enforcement Matters
    - MURs content (include distinction between `current` and `archived` MURs per demo)
    - Approach for other asset types that fall under Enforcement but will not be available (`Coming soon`?)

**Comment by porta-antiporta** [comment]
cc: @jenniferthibault as we will likely need a viz-d looksie once the content is drafted.

**Comment by emileighoutlaw** [comment]
Draft is completed and with FEC for review. I'll keep folks posted on the progress here.

**Comment by jenniferthibault** [comment]
Thanks @emileighoutlaw I am keeping my 👀 open for content coming in on this.

**Comment by porta-antiporta** [comment]
Posting link of draft here for visibility: https://docs.google.com/document/d/162wHmoUz0M8JWUYP1iXRUSRvPabSv_cnycRWJ3DYhF8/edit#

**Comment by jenniferthibault** [comment]
@emileighoutlaw quick check, is this still with the FEC for review?

**Comment by emileighoutlaw** [comment]
Yep — still with FEC

**Comment by jenniferthibault** [comment]
Done and merged in!
