### ISSUE TITLE
Advisory opinion content for migration to betaFEC

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-eregs#241]
One of our priority tasks for migration is to move all advisory opinion supporting content to betaFEC. To do this:

- [x] identify all advisory opinion content
- [x] reorganize to fit into refined, beta site structure
- [x] consider content edits
- [x] FEC review
- move to design/implementation
- add content to universal search / specific asset type search (including design, API work to index this content once migrated, and UI to display search hits etc. to support this)

**Comment by emileighoutlaw** [comment]
@AmyKort — I took a look at the website and content inventory. This is the full set of content I could find on advisory opinions on FEC.gov:

- Advisory opinon brochure (HTML): http://www.fec.gov/pages/brochures/ao.shtml
- Advisory opinion brochure (PDF): http://www.fec.gov/pages/brochures/ao_brochure.pdf
- Advisory opinion statistics (PDF): http://www.fec.gov/law/policy/enforcement/2009/ao05-09.pdf
- How to comment on an advisory opinion (HTML): http://www.fec.gov/law/proposed_rule_comment.shtml
- Internal procedures for advisory opinions (HTML): http://www.fec.gov/law/draftaos.shtml


Can we check with legal folks and see if anything is missing from that list? If it's complete, we can start making a plan for how to move it over to beta!

**Comment by porta-antiporta** [comment]
IMHO this content, once migrated, should also be included in the universal search / specific asset type search.  There will need to be design, API work to index this content once migrated, and UI to display search hits etc. to support this.

**Comment by emileighoutlaw** [comment]
Great thought. Added that to our list of things to do, Porta.

**Comment by AmyKort** [comment]
That would be fantastic!

**Comment by emileighoutlaw** [comment]
Any word on how we want to proceed with this @AmyKort ?

**Comment by AmyKort** [comment]
Looks good to me. I'm still waiting on word from the legal folks--I kind of overwhelmed them last week with requests for help.

**Comment by AmyKort** [comment]
We're good to go!

**Comment by emileighoutlaw** [comment]
From my perspective, the best approach forward would be to have a single page of information about advisory opinions, which draws from the brochure and other pages. 

In my dream world (of ideological content strategy), that single page of content about advisory opinions would be all we need, but I understand why keeping the brochures (and keeping them as is) is an important thing. So we can additionally add a link to the PDF brochure from our new page of information about advisory opinions. 

I'll dive in now, and we can talk soon!

**Comment by AmyKort** [comment]
Sounds good. I think the brochure information is also in HTML on our current site, so I don't think we'd have to use the pdf version. Thoughts?

**Comment by emileighoutlaw** [comment]
Yes I totally agree! 👯

**Comment by emileighoutlaw** [comment]
This is done and approved! Moving to implementation: https://github.com/18F/fec-eregs/issues/290
