### ISSUE TITLE
Update designs for enforcement matter search page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-eregs#243]
The older mockups are out of date with the current patterns enough that it's worth a fresh mockup.
- Old mockup: https://gsa.invisionapp.com/share/AR7U3Y662#/screens/167711268

Splitting this into a separate issue because I'm having trouble following in the implementation issues. When these get 👍 'ed & questions are sorted here, I'll carry over final designs to the implementation issue in https://github.com/18F/fec-eregs/issues/226
 
- [x] Mockup for desktop
- [x] Mockup for mobile

**Comment by porta-antiporta** [comment]
Could we include in the mockup how a current vs. archived MUR looks like in the search results.  The old mockup focused mostly on the current MUR.  

Also, I don't think we should group archived MURs and then current MURs (like is done on fec.gov) as it feels like the search results should be displayed in order of search term relevance; but figure I'd surface that here for debate as well.

**Comment by jenniferthibault** [comment]
_Note: totally junk placeholder returned MUR results, titles, names, etc. Consider it no better than Lorem ipsum._ 

@porta-antiporta having a mixed feed of archived/current MURs based on the relevance of the match makes sense to me. When searching, you want to best match, and the distinction between archived/current is a structure created by the FEC, not by the user. These mockups show what a mixed feed would look like.

**Other changes**
- Since we are using faceted search here, we should follow the tag-generating pattern (and thus, layout pattern) already established for this in the [data tables](https://beta.fec.gov/data/candidates/president/?election_year=2016&cycle=2016&election_full=true) and [calendar](https://beta.fec.gov/calendar/?category=election).
- I re-prioritized the match results (snippet) above the other MUR details, since that feels more expected for a search result pattern. 
- To simplify the table layout, I've also moved the `Date closed` , `Disposition`, and `Documents` fields to part of the main "Matches" column instead of their own columns. This avoids needing to have multiple column/field widths within one result, and keeps priority on the text matches

## Desktop

![enforcement search copy 2](https://cloud.githubusercontent.com/assets/11636908/18147958/18bd677a-6fa5-11e6-93ad-ff1d16014d38.png)



## Mobile

Continues to use the base filter/tag panel pattern for viewing/closing the filter panel.

### Editing filters
- ![filters and tags mobile expanded](https://cloud.githubusercontent.com/assets/11636908/18147768/24b408f0-6fa4-11e6-968c-7c4126237eb1.png)

### Filter panel closed, viewing results
- `Date closed` , `Disposition`, and `Documents` fields to simplify and shorten results (not 100% sure on this, thoughts?)

- ![filters and tags mobile closed copy](https://cloud.githubusercontent.com/assets/11636908/18147769/2719b81a-6fa4-11e6-9df4-b1cfe5adf161.png)

**Comment by porta-antiporta** [comment]
❤️  the new designs and layout @jenniferthibault!  Particularly having clarity on what we should be displaying for mobile.

Had a couple comments that just came to mind:

* Archived MURs:  Disposition and Documents.  To be nitpicky they _are_ available for archived cases.  The user has to actually read the pdf and find the disposition (or count the number of docs).  So perhaps we should look at different _words_?

* Commented on #220 as well as it may be more an API question, but MURs have `Subjects` which are like topics.  Those subjects _may_ never appear in the actual text of the MURs.  If that is the case, what pattern should we use to display that a search hit was due to a match on `topic` as opposed to `text` within the MUR case?  I indicate pattern as this could also apply to advisory opinions down the line (if we ever proceed to merge infoweb topic tags to the advisory opinion cases).

**Comment by porta-antiporta** [comment]
I should iterate my 💟 for displaying separately what filters/facets are `active` from what filters can be added.  It really adds clarity for power users; helping them understand what's narrowing down the results.

**Comment by jenniferthibault** [comment]
Good point on the unavailability language! I'd like to tag in Emileigh to take a look at that before this issue is complete, but hold off on that until the additions to the layout are complete in case there's other stuff we want her help with.

To include the subject for current and archived MURs, we could do something like this:

<img width="744" alt="screen shot 2016-09-01 at 4 17 50 am" src="https://cloud.githubusercontent.com/assets/11636908/18160362/1d65a5f2-6ffb-11e6-86c6-47e1d24e3ff7.png">

This takes the subjects for current MURS exactly as they are, (as a text list) and turns the subject in Archived MURs from a bulleted list to a text list.

<img width="1062" alt="screen shot 2016-09-01 at 4 20 30 am" src="https://cloud.githubusercontent.com/assets/11636908/18160439/868b0ed2-6ffb-11e6-865c-72f1626c896c.png">
<img width="679" alt="screen shot 2016-09-01 at 4 20 38 am" src="https://cloud.githubusercontent.com/assets/11636908/18160440/868dd91e-6ffb-11e6-90fb-f7f11cc6b80b.png">


Though on mobile that makes me wonder if we should keep the whole section below the snippet, instead of hiding it as we were previously:

<img width="324" alt="screen shot 2016-09-01 at 4 28 33 am" src="https://cloud.githubusercontent.com/assets/11636908/18160735/af6442f0-6ffc-11e6-8155-0d0c5d0e5548.png">

**Comment by jenniferthibault** [comment]
@porta-antiporta do you think this design is ok to start with? Or any other considerations?

If so, I'll ping in Emileigh & give her some context on what language we could use help on.

**Comment by porta-antiporta** [comment]
@jenniferthibault I think we are :+1: to go.  

Re: `Subject`, got a response from @anthonygarvan  that the API currently will not prioritize matches on a `Subject`.  i.e. It treats it the same as a match on text; unlike a match on `case number` which gets priority.  With that in mind, I think we are good with not displaying the `Subject` view on mobile.

**Comment by jenniferthibault** [comment]
@porta-antiporta ok so sounds like reverting back to the designs from [the first comment here](https://github.com/18F/fec-eregs/issues/243#issuecomment-243917255)?


👋 @emileighoutlaw! Come on down for a microcopy question 💃 💃 💃 💃 

In FEC Land, there are two kinds of MUR records: 
- **Current MURs:** which are from 1998-ish to present, and are cases that have been entered into a rich text database. You can find one of those by searching around their "[Enforcement Query System](http://eqs.fec.gov/eqs/searcheqs?SUBMIT=summary&key=0)". 

- **Archived MURs:** which are from before 1998 and exist _mainly_ in PDFs. These also have a few fields that have been pulled out, but they don't have all the same info available and searchable in a rich text format that current MURs do. You can see these on their [Archive](http://www.fec.gov/MUR/)

This means that when we show a search results page, Current MURs will have some fields filled in that Archived MURs don't. Porta rightly pointed out that this information _exists_ in the PDF, but it isn't able to be searched/returned by a computer, and thus made available here. Where we'd like your expert help is how we communicate why those fields aren't filled in on the search page. 

Questions? Thoughts? Answers? Ice cream?

_Example:_
<img width="834" alt="screen shot 2016-09-02 at 1 58 10 pm" src="https://cloud.githubusercontent.com/assets/11636908/18213250/5171faba-7115-11e6-955f-50b6ce216c86.png">

**Comment by porta-antiporta** [comment]
@jenniferthibault on including `summary` in the results list or not; i am :neutral_face: On the one hand, it seems this is valuable information if fec shows it for current and archived MURs.  On the other, that information is present on the canonical page and have concerns of screen real estate.

Would an option be include the `Subject` but make those fields after the snippet expandable/collapsable? But really I'm way out of my depth here in terms of solid design patterns.  Your thoughts?

**Comment by jenniferthibault** [comment]
It's _always_ an option @porta-antiporta ! Just maybe not a great one here. I'd recommend against a show/hide interaction on a search results page like this. The objective is to return information that will help a user determine which canonical MUR best answers their search/questions, and as efficiently as we can. We should include the bare minimum bits of information a user needs to make this determination, and have it right up front. Anything hidden behind a click might as well be on the secondary (canonical) page instead of the search.

**What I don't know:** Which bits are the ones a user looks most to for determining which MUR they want to open.
**For the first iteration:** My hunch (knowing very little about MURs) is that year is helpful, because it helps determine recency and relevance. Subject, probably also helpful because it gives general categorization. Document count & Disposition are details, not things that help me choose between two MURs. So I'd keep Year & Subject, but remove Document count and Disposition from the search results. 
- It also has the nice side effect of solving our (and @emileighoutlaw 's future) microcopy, since we've eliminated those fields from the search results here.

<img width="638" alt="screen shot 2016-09-02 at 4 27 36 pm" src="https://cloud.githubusercontent.com/assets/11636908/18217359/51cc28ea-712a-11e6-8936-0976f36d1a9c.png">

**Comment by jenniferthibault** [comment]
If we're ok with this as a first step, I've updated the following with the layouts:
- desktop InVision: https://gsa.invisionapp.com/share/S58HMFKMB#/185960388_Enforcement_-_Search
- mobile InVision: https://gsa.invisionapp.com/share/MA8ID5U6Z#/186537529_Enforcement_Search-Mobile

Which I'll copy over to #226 and we can close this issue. @porta-antiporta 👍 ?

**Comment by porta-antiporta** [comment]
:+1: @jenniferthibault.  Awesome thanks!
