### ISSUE TITLE
Update designs for MUR canonical page (archived and current)

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-eregs#244]
Started in https://github.com/18F/fec-eregs/issues/220 but splitting out the designs as a discrete task so that we can keep the back end loading separate from the design.

Remaining tasks:
- [x] Update headline structure on Archived MURs to incorporate title
- [x] Desktop mockups
- [x] Mobile mockups

**Comment by jenniferthibault** [comment]
Alrighty, sorry this took so long, there are a bunch of tiny line details. But now these are all up to date with the latest styles and title structure AND we have mobile concepts.

## Current MUR

**Open questions:** 
(cc @porta-antiporta )

- What is a "Disgorgement?" They were in Ed's mockups, but with no more info than a placeholder title
<img width="510" alt="screen shot 2016-09-02 at 1 33 51 pm" src="https://cloud.githubusercontent.com/assets/11636908/18212590/00fcfb0a-7112-11e6-9b8c-70dcfef4ee59.png">

- What's the general sense of the "TBD" column under the Participants table?
<img width="511" alt="screen shot 2016-09-02 at 1 34 00 pm" src="https://cloud.githubusercontent.com/assets/11636908/18212594/069cad8a-7112-11e6-8a0c-d0a4c2eb7a08.png">

### Desktop

![mur-canonical-desktop](https://cloud.githubusercontent.com/assets/11636908/18212508/9fe9ee18-7111-11e6-9c1a-2a91d080f532.png)

### Mobile
![mur-canonical-mobile](https://cloud.githubusercontent.com/assets/11636908/18212609/20b2b034-7112-11e6-926b-1b3a94d9175d.png)

To hold all the info, the tables will use the expanding pattern used in the data tables:
<img width="709" alt="screen shot 2016-09-02 at 1 36 11 pm" src="https://cloud.githubusercontent.com/assets/11636908/18212651/5cc47dfa-7112-11e6-8f61-93668e454ac2.png">

<img width="700" alt="screen shot 2016-09-02 at 1 36 27 pm" src="https://cloud.githubusercontent.com/assets/11636908/18212652/5cc6fe90-7112-11e6-86ee-f0041ac120ce.png">

## Archived MUR

### Desktop

![mur-archived-canonical-desktop](https://cloud.githubusercontent.com/assets/11636908/18212689/8345c3f8-7112-11e6-97cb-10dd9ec76ec4.png)

### Mobile

![mur-archived-canonical-mobile](https://cloud.githubusercontent.com/assets/11636908/18212690/83497b1a-7112-11e6-813c-4688ab6dcef8.png)

**Comment by porta-antiporta** [comment]
@jenniferthibault FTW :trophy: 

re: TBD and `disgorgements`.
* Disgorgements were a field that is on the current MUR canonical pages on FEC.gov.  Have a question to our awesome partners in slack to understand the difference between that and penalties.
* TBD IIRC, there were also information regarding the firms representing the participants. But we can leave that off for now

**Comment by porta-antiporta** [comment]
Also, could I have a link to the `Sketch` files?  I'd like to update our Invision mockups to reflect the new designs before I meet with the FEC next Thursday.

**Comment by porta-antiporta** [comment]
From Amy:

> let's say I am a political committee and I accepted impermissible contributions from an impermissible source. I can't keep those funds and use them. I have to take that money out of my account. That's a disgorgement. Often  disgorgements are made to the U.S. treasury. The penalty is a separate issue. In addition to not being able to use that impermissible money, I also have to pay a fine.

So in the mockup, the `Name` would be the entity that had to restitute those monies.

**Comment by jenniferthibault** [comment]
Thanks @porta-antiporta ! Sounds like it would be beneficial to have a glossary term (at least) here. Maybe even a quick overview, so I added in a little placeholder text.

<img width="862" alt="screen shot 2016-09-02 at 3 55 14 pm" src="https://cloud.githubusercontent.com/assets/11636908/18216613/d9b4ec74-7125-11e6-9552-2a0bc6b03d69.png">

Glad you mentioned the InVision! I duplicated `legal-v4` and made a `legal-v5`! today for just this purpose. https://gsa.invisionapp.com/d/main/#/console/8681897/185960388/preview

Since we're still in the middle of making design changes, I don't mind updating these to spec as you need, that way we're not having to update two sets of Sketch files? Also open to other ideas, I don't understand how in 2016 there still isn't a great solution for how to get multiple designers access to the same design files at once!

**Comment by porta-antiporta** [comment]
awesome @jenniferthibault saves me ton of work.  ty!

i was actually going to ask how the design chapter 'version controls' their artifacts.  unfortunately GH only allows very specific attachment filetypes (and i don't want to have to zip a sketch file every single time i want to upload it to GH).

**Comment by jenniferthibault** [comment]
So far, version control happens by keeping the master design files with one or two designers on their local machines, and having lots of back & forth between interaction designers & visual designers. Or, sometimes hosting the files on Google Drive or GitHub when things are wrapped up, or on pause. There's no great way 😞 

I totally consider updating InVision files a design task, (and it makes it easier for the master design files to be with one place/person at a time) , so glad to keep taking this on in the future.

For the current issue, it sounds like we've hit a good spot to move into front end. I've updated the following files with the designs:
- desktop InVision: 
  - [current MUR](https://gsa.invisionapp.com/share/S58HMFKMB#/185960395_MUR_Canonical)
  - [archived MUR](https://gsa.invisionapp.com/share/S58HMFKMB#/185961446_MUR-Archived-Canonical-Desktop) 
- mobile InVision:
  - [current MUR](https://gsa.invisionapp.com/share/MA8ID5U6Z#/186537552_MUR-Canonical-Mobile)
  - [archived MUR](https://gsa.invisionapp.com/share/MA8ID5U6Z#/186537551_MUR-Archived-Canonical-Mobile)

 I'll copy these over to #220 and we can close this issue.
