### ISSUE TITLE
Unexpected search results

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#245]
Searching statutes for "30101(4)" doesn't give section 30101 as a hit.  And searching AOs for "2015-01" produces either all AOs (if you omit the quotation marks) or zero AOs (if you include the quotation marks).

**Comment by porta-antiporta** [comment]
@PaulClark2 Going to consolidate this into #247 (which will become an epic once zenhub has addressed the bug) as the different symptoms are actually separate issues so calling them out specifically. Pls track under that epic and will be closing this issue.
