### ISSUE TITLE
Unexpected search results

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#246]
We ran separate AO, statutory and E-Reg searches.  None of them produced results that we expect:

Basically each time we ran a search, the statutory or reg cite and the AO for which we were searching wasn’t even in the hit list.  This goes back to the need to be able to put in a cite (for any of those three things – and MURs when they are up) and get that specific statutory or reg cite or that particular AO – not everything that cites to our search term.

Further, when we searched for 2015-01 – we got 1300+ hits (which is basically all of our AOs) and the related documents listed under the hits we did get, were random – some had the request, some didn’t (and these were NOT the pre1990 AOs for which we don’t have the related documents in the our database).

**Comment by porta-antiporta** [comment]
@PaulClark2 Going to consolidate this into #247 (which will become an epic once zenhub has addressed the bug) as the different symptoms are actually separate issues so calling them out specifically.  Pls track under that epic and will be closing this issue.
