### ISSUE TITLE
Unexpected Search Results

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#247]
The following have been reported by internal FEC users regarding unexpected search results.

- [x] `109.20` does not show up as a regulation in the search results
- [ ] `2015-01` results in over 1300 results
- [x] `"2015-01"` does not result in a hit 
- [ ] `30101(4`) does not result in section 30101 showing up as a result for statutes

see below comments for resulting outcomes for above.

**Comment by porta-antiporta** [comment]
109.20 not shoing up as a regulation has been addressed and deployed to production as part of: https://github.com/18F/openFEC/pull/1930

**Comment by porta-antiporta** [comment]
`2015-01` resulting in 1300+ hits.

The high number of hits is expected behavior as the code will match on `2015-01`, `2015`, `01`.  
However, what is confusing is that the highlights don't return what matched.  So will need to address that.

**Comment by porta-antiporta** [comment]
`"2015-01"` not returning any hits.

This has been addressed via the following PR: https://github.com/18F/openFEC/pull/1917

**Comment by porta-antiporta** [comment]
`30101(4)` does not return section 30101 as a hit

We will likely need to implement some specialized parsing that recognizes subsections so it can search for that as well.

**Comment by adrianwebb** [comment]
Moved to Epic in fec-epics: https://github.com/18F/fec-epics/issues/34
