### ISSUE TITLE
Advanced search functionality

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#259]
Epic to track advanced search functionality currently in our backlog.  Will likely need to break this epic down into multiple epics.

The findings from the co-design sessions were that users were requesting the following advanced search functionality (https://docs.google.com/document/d/1YiXW9sYA_qXQmeomt721uNi-BJ04P1wqk9J6JsnNTHQ/edit)

**Derivative search**. A smart search mechanism that knows to include variations on word forms. For example, a search for the word “walk” might also include “walks,” “walking,” and “walked.” 

**Boolean search**. This kind of search allows users to combine or exclude search terms by using operators, such as AND, OR, and NOT. 

**Proximity**. A smart search mechanism that looks for the appearance of specific terms in close proximity to each other (for example, in the same sentence or paragraph).

**Search within search**. The participants expressed an interest in performing a sequence of text searches to increasingly narrow their results. After receiving their first round of search results, they wanted to search again, but only within those results.

**Chronological results**. Some participants explained that they would like to be able to view results by a specific year, or a set of years. (For example: Show me everything on this topic from 2010 and beyond.)

**Step through document by keyword**. Some participants expressed an interest in being able to search within the actual documents for the keywords they searched. On this note, there was some acknowledgement that CTRL + F (or similar) can accomplish this.

The goal of this story is to:
- [ ] Determine patterns we will use to create **Boolean Search** (Google patterns?)
    - AND search
    - OR search
- [ ] Design help / assisted help tools (i.e. how to use advanced search)
- [ ] Determine re-use of existing faceting patterns used on Data
- [ ] If so, enhance those patterns to show how boolean search will be displayed

Note, that while the story focuses on Boolean Search, included the other findings so that the design be more forward thinking.

**Comment by adrianwebb** [comment]
Moved Epic to fec-epics: https://github.com/18F/fec-epics/issues/33
