### ISSUE TITLE
Moderated sessions at the FEC

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#260]
@nickykrause @adrianwebb @porta-antiporta will be at the FEC 9/21 & 9/22.

Several emails, slacks, issues have been logged discussing the lack of advanced functionality with our current universal search.

During these sessions, our goal is to understand what internal FEC users need maximize their use of the new system.

**Comment by nickykrause** [comment]
Sessions have been designed, conducted, synthesized, and discussed with the FEC. 

Documentation is here: https://drive.google.com/drive/folders/0B8u6AetkKiTUb1pzeFgxVjQ2Z1E

**Comment by jenniferthibault** [comment]
Is this ok to close?

**Comment by nickykrause** [comment]
Seems ok to me, yes
