### ISSUE TITLE
Statutory citations in archived MURs

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#263]
In 2014, the statutes that the FEC administers were remapped from Title 2 to Title 52 of USC.
The mapping of those is contained in the following location in various formats (pdf and html)
http://uscode.house.gov/editorialreclassification/t52/index.html

However, old documents such as archived MURs cite the old statute numbers (Title 2).

Because of this, on the archived MUR page link to an outdated citation, and therefor the incorrect statute.  https://fec-dev-proxy.18f.gov/data/legal/matter-under-review/3543/

Need to point archived MURs to point to the updated location.

Implementation note:
* Archived MURs is not the only place where this issue will arise.  So when balancing the timeframe we have and other potential occurrences (current MURs, AO citations) consider if there is a solution that could be extended to cover those occurrences. 
* But, archived MURs have the higher priority (so if just correcting the citations in the data itself for archived MURs is all we can commit to, lets take that route).

- [x] Swap GPO citation link from pdf to the html version

**Comment by adborden** [comment]
Here's a table mapping the old sections to the new ones.
http://uscode.house.gov/editorialreclassification/t52/Reclassifications_Title_52.html
