### ISSUE TITLE
Regulatory URLs in archived and current MURs

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#264]
Initially, we did not point the URL for regulatory citations in archived MURs to our eregs implementation.  We pointed it to the GPO API as we were unsure whether all regulatory citations referred to 11 CFR.

After further analysis and consideration, we determined that regulatory citations for archived MURs do all point to 11 CFR.

So lets update the URLs for archived MURs to point to the eregulations instead of the GPO API

**Comment by vrajmohan** [comment]
https://github.com/18F/openFEC/pull/1965 fixes this for future loads. I'll create a utility to fix the links in MURs already loaded.

**Comment by vrajmohan** [comment]
https://github.com/18F/openFEC/pull/1961 remaps both statutory and regulatory citations and will therefore take care of this. There is no need for a separate utility for this.
