### ISSUE TITLE
Only search 'Final Opinion' document type when searching AOs

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#266]
Feedback from sessions on 9/21 and 9/22 at the FEC is that researchers only search for final opinions when conducting a search (at least by default).  99% of the time, they are first concerned with what the Commission has had to write on the subject.

So need to update the search so that it only searches final opinions.  This will mean that the search results will only have 1 type of document.

**Comment by porta-antiporta** [comment]
Implementation note:  Filtering should only impact category for advisory opinions.

**Comment by adrianwebb** [comment]
Close out letter labels should look different than final opinions
