### ISSUE TITLE
User loses context of search when they go to canonical

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#267]
## Discuss in grooming whether this story should be kept in the backlog or closed out.  Namely, will search and refinement suffice?

When the user goes from the search results to the canonical page, they lose context of what documents contain those search terms.  Furthermore, #266 will limit the search to only be in final opinions.

Need to be able to provide the user an understanding of what docs contain those search terms on the canonical page.
- [ ] Update design to display this
- [ ] Update API to return this information (if search query is passed)
  - [ ] Need to be able to handle situation if no query is passed (i.e. user went to canonical page directly)
- [ ] Update web app to pass search query when going from search results to canonical

**Comment by porta-antiporta** [comment]
@adrianwebb There is an open discussion as to whether this is really necessary or not.  Some background:

* Users had commented in usability that when they went from search results to canonical page they didn't remember which docs had the search terms.
* However, can this can be accomplished using search refinement 
* Perhaps worth testing again to see if it is needed once refinement is available.

**Comment by jenniferthibault** [comment]
@emileighoutlaw @nickykrause and I chatted about this, and we think it makes sense to hold off on starting this design task until we've implemented and tested the new AO filters that return only Final Opinions unless the user adds more document types.  Going to keep it in the backlog.

**Comment by jenniferthibault** [comment]
I did a little bit of thinking toward this when looking at how the search results list would change based on only returning the final opinion until the user adds more document types:

If a user did a search for "filing" and only returned final opinions (as default), this AO would look like this:

<img width="738" alt="screen shot 2016-11-08 at 9 42 41 am" src="https://cloud.githubusercontent.com/assets/11636908/20103393/d487d60c-a597-11e6-9594-3d73d7e8f5b0.png">

- the AO name links to the AO canonical page
- the "Final opinion" document title would link directly to that document

If a user did a search for "filing" and added a "Draft documents" document type filter, the same AO results would look like this:

<img width="742" alt="screen shot 2016-11-08 at 9 42 47 am" src="https://cloud.githubusercontent.com/assets/11636908/20103432/fefdef3e-a597-11e6-8687-ed5d9ab1e40a.png">

- the AO name links to the AO canonical page
- the "Final opinion" document title would link directly to the final opinion document
- the "Draft AO (OGC), Agenda Document No. 96-53" title would link directly to that document

This means a matching excerpt is surfaced from each document type returned, enabling the user to see the context of the match in different documents, and link directly to them.

**Comment by nickykrause** [comment]
@jenniferthibault - Yes, I agree. I think this is is one of the reasons that this story is still sitting with the initial question: "Will search and refinement suffice?" It seems likely that the functionality we're implementing for the AO search/refinement experience will resolve this issue, or reveal that it is a non-issue. (If we didn't include the other document types as filters, this probably would have been a problem -- we'd only be showing highlighted search terms for final opinion docs, and nothing else.)

When we test the AO filters, we can include questions and probes to get at this issue, but even the "test" you've documented is suggestive that the link directly to the different document types will be sufficient.

Would it make sense to close this issue and re-open it only if it indeed surfaces as a user complaint during testing?

(I added this to the existing testing idea in the testing repo: https://github.com/18F/fec-testing/issues/12)
