### ISSUE TITLE
Update citations on current MURs to reference 52 USC

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#270]
The current citations only reference the section of 52 USC for current MURs; whereas archived MURs include 52 USC (once we're done with #263).  Need to make those consistent.

**Comment by adborden** [comment]
It looks like this is already done https://github.com/18F/openFEC/blob/ea4231444872a04b9fa0b732fba3e4ce82a57c15/webservices/load_current_murs.py#L154

**Comment by vrajmohan** [comment]
I thought that this story was intended for _archived_ MURs

**Comment by adborden** [comment]
This story is for current MURs. There is a separate story for [archived MURs](https://github.com/18F/fec-eregs/issues/263)

**Comment by porta-antiporta** [comment]
@vrajmohan @adborden  This story is to update the link text to be `52 U.S.C <section number>`  For current MURs we only list <section number>.   If you look at a current MUR and archived MUR canonical you see on archived its `52 USC 30101` wherease on current its just `30101`

**Comment by vrajmohan** [comment]
This is fixed by https://github.com/18F/openFEC/pull/1965.
