### ISSUE TITLE
Content for complaints

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-eregs#272]
Create introductory content and supporting publications for complaints. 
- [x] Audit existing content
- [x] Draft new content
- [x] FEC review
- [ ] Implementation

Existing content: 
- Complaint guide http://www.fec.gov/em/respondent_guide.pdf
- Complaint brochure: http://www.fec.gov/pages/brochures/complain.shtml
- Complaint content in FAQs: http://www.fec.gov/ans/answers_compliance.shtml

**Comment by adrianwebb** [comment]
Goal for sprint 25 is drafting content and FEC review

**Comment by emileighoutlaw** [comment]
Update time! 🎉 


The existing, [Filing a complaint](http://www.fec.gov/pages/brochures/complain.shtml) brochure provides detailed information about how to file a complaint and what happens at each stage of the complaint lifecycle. The existing, [Guidebook for Complainants and Respondents on the FEC Enforcement Process ](http://www.fec.gov/em/respondent_guide.pdf)dives even deeper into the process and requirements. 

Both are commission-approved publications and need to port to the beta site as is.

So as I was starting to think of a content draft, I was left with a tricky strategy problem. I didn’t want to reinvent the wheel— it doesn’t make sense to cover the same information in the same way multiple places. 

So I did some hunting and found inspiration on the CFPB’s complaint page: http://www.consumerfinance.gov/complaint/process/

Their process page is brief, helpful, friendly and actionable. So I started thinking about this complaint landing in the same way, as a page of orientation, a page where users can start to understand the process and _then_ decide whether they really want to dig deeper into filing a complaint or learning more about responding.

[So I have a draft of content](https://docs.google.com/document/d/1XctsE8Lh5A2NCePAAhisyPVi-y4Az9CtIyNh8mtF7Zs/edit#) :lock: I'd love you to take a look at @amykort. I think this could be a really cool and clear approach to content that is still aligned with our "one content: one place" principle.

Let me know what you think of this idea! If you like it, I can make it a Word Document for official editing and review.

**Comment by emileighoutlaw** [comment]
Ping @amykort

**Comment by noahmanger** [comment]
**Criteria for completion for sprint 1:**
- [ ] Draft content and send to OGC for review

**Comment by AmyKort** [comment]
I think this is ready to go out fire view. Thanks for your patience!

**Comment by AmyKort** [comment]
Ahem. For review

**Comment by emileighoutlaw** [comment]
Woohoo! I'll forward you a Word Document via email that we can send around :)

**Comment by emileighoutlaw** [comment]
Amy has forwarded to OGC. So we're done! Woo!

**Comment by AmyKort** [comment]
Only one comment, which is to change the 2 USC 437g citation to 52 USC 30109. Thanks!
