### ISSUE TITLE
Identify and design search results refinement patterns for AOs

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-eregs#274]
### why this issue was created
The findings of the co-design sessions with legal users at the FEC suggested that users are interested in tools that will allow them to narrow their search results when searching through legal documents, including Regulations, AOs, MURs, etc. 

_For more detailed information about this and other research outcomes, see the [full synthesis of the co-design sessions](https://docs.google.com/document/d/1YiXW9sYA_qXQmeomt721uNi-BJ04P1wqk9J6JsnNTHQ/edit)._

---

### scope of this issue
Recognizing that there will most likely be different "refinement" needs for different document types, this issue deals specifically with **refining search results for Advisory Opinions (AOs)**. 

Furthermore, **this issue deals with the design of the refinement tools for AO searches**, and not with implementation. 

---

### relationship to other issues
This is closely related to issue #266: "Only search 'Final Opinion' when searching for AOs."

During the co-design sessions, we found that users who are searching across AOs are primarily interested in reading the **Final Opinion** (a specific document within the AO). After reviewing the final opinion, they may become interested in viewing other documents within the AO (e.g., commissioner statements, votes). 

So, **a key design challenge that we have** which is shared across both of these issues is as follows: 

`How do we design an AO search & results refinement experience that accommodates users' preference for prioritizing relevant Final Opinions over other AO documents that are only of secondary interest?`

---

#### rationale and background on AO-only search
Importantly, the legal search mechanism that we currently have on betaFEC operates by searching _document types_ for specific keywords. It then ranks those document types for display by identifying which individual documents contain the greatest number of relevant key words. 

Consequently, in the case where there are two documents within a single AO that contain the user's search terms, it is possible that one of those documents (let's say, a Commissioner's Statement) will have far more search-term-matches than the other document (let's say, the Final Opinion). In that case, the Commissioner Statement from the AO would appear closer to the top of the search results, while the Final Opinion from that AO would appear much lower in the results list. Based on the co-design session data, this situation is not ideal.

One possible solution to this problem would be to change the search mechanism, such that it (a) searches all document types for instances of the search terms, (b) _groups the search results by AO_, and then (c) ranks those groupings against each other, in order of relevance (somehow). No matter what, the AO groupings would always need to include some kind of link to the final opinion, even if the final opinion didn't contain the search terms. 

This solution raises several concerns:
- Per @porta-antiporta, altering the search functionality in this manner would require a large technical lift and would have implications for the API
- This solution is being suggested in the absence of advanced search features and results refinement tools, which, if they were present, may eliminate the need for this kind of change to the search results display. 

In light of all this, the question of how to handle AO searches has settled, temporarily, with the solution to display results only for Final Opinions (as issue #266 directs). One reason for this being the immediate solution is that we had previously implemented this exact development solution before switching to the results display described above, so it is a fairly straightforward matter to switch back.

And, finally, **the design takeaway** for this issue is:

`How, if at all, can the AO results refinement tools (e.g., filters) assist users in prioritizing Final Opinions over other document types?`

---

### previous work on AO results refinement
There are already InVision mockups that suggest that need for AO results refinement, but the refinement mechanisms that appear there are based primarily on the filtering capabilities of users' previous systems. 

**Additional information that we need**:
`What refinement mechanisms would make the most sense for parsing AO search results, from the users' perspective?`

Furthermore, we already have filtering mechanisms in place on the data side of betaFEC, so there is an opportunity to leverage our knowledge about usability from those features, and to maintain consistency throughout the site.

This begs **yet another question**:
`How, if at all, can we leverage the design patterns for filtering mechanisms available on the data side?`

---

### completion criteria

- [ ] Identify the refinement mechanisms that will be most useful for users who are parsing AO search results
- [ ] Design the relevant refinement mechanisms while maintaining as much consistency as possible with the data side

Vague criterion?:
- [ ] Consider the bigger picture of the full experience while addressing this issue. This includes AO search, results refinement, drilling down into AOs beyond final opinions. What does this experience look like?

**Comment by nickykrause** [comment]
### some reference materials
Link to existing AO search on fec.gov: http://saos.fec.gov/saos/searchao

Screenshot of **advanced search options** for existing AO search:

![ao_advaned_search](https://cloud.githubusercontent.com/assets/1450173/18972030/2396a0fc-865d-11e6-8713-dc0cd9a78ee9.png)

Screenshot of **results display** for existing AO search:
![ao_search_results](https://cloud.githubusercontent.com/assets/1450173/18972101/66cf803c-865d-11e6-9d31-893f0e3b17dc.png)

Screenshot of **refine search** option for results display in existing AO search:
![ao_refine_results](https://cloud.githubusercontent.com/assets/1450173/18972119/76aa54b4-865d-11e6-941e-5f04a53e1ca3.png)

**Comment by nickykrause** [comment]
For reference: excerpt of Ed Mullen's past mockups for AO search: ![image](https://cloud.githubusercontent.com/assets/1450173/18997805/b6da5bd0-86fb-11e6-929d-fbef2db8d994.png)

**Comment by nickykrause** [comment]
For reference: An excerpt of Ed Mullen's previous mockups for AO search, showing AO filters:
![image](https://cloud.githubusercontent.com/assets/1450173/18998032/9337e6f6-86fc-11e6-9fcc-52fa32d92be2.png)

**Comment by nickykrause** [comment]
A list of the current advanced search / filtering options for AOs:

- AO number (search box)
- AO Name (search box)
- AO document type (checklist)
    - Final Opinion
    - AO Request, Supplemental Material, and Extensions of Time
    - Draft Documents
    - Votes
    - Withdrawal of Request
    - Comments and ex parte communications
    - Commissioner Statements
    - All categories
- AO Request Date (date range)
- AO Issued Date (date range)
- Entity (drop-down menu)
    - Requestor
    - Counsel/Representative
    - Commenter
- Entity Type (conditional drop-down menu)
    - Federal candidate/candidate committee/officeholder
    - Publicly funded candidates/committees
    - Party committees, national
    - Party committees, state or local
    - Nonconnected political committee
    - Separate segregated fund
    - Labor Organization
    - Trade Organization
    - Membership Organization, Cooperative, Corporation W/O Capital Stock
    - Corporation (including LLCs electing corporate status)
    - Partnership (including LLCs electing corporate status)
    - Governmental entity
    - Individual
    - Research/Public Interest/Educational Institution [for commenters only]
    - Law firm [for commenters or counsel/representative only]
    - Other
- Entity Name (search box)
- Browse by year (links to results, confined to selected year)
- Pending AO Requests (links to a list of the pending requests)

**Comment by nickykrause** [comment]
Update: I reached out to Cheryl at FEC to gather her thoughts on which of the items from that list have actually proven useful to her. (asking, e.g., which of these do you actually use? Are there some you never use?).

She volunteered to pass around to some other colleagues, who will also be providing there input. Input should come by end-of-day Tues at the latest.

**Comment by nickykrause** [comment]
Per @anthonygarvan, this is the current AO filter list tagged to show which filters are currently supported on beta ("Y"), and which would require some work ("N"). Also, one more note from Tony:

> most of those are not currently supported, but all the data is there

- AO number (search box) Y
- AO Name (search box) Y
- AO document type (checklist) Y
- AO Request Date (date range) N
- AO Issued Date (date range) N
- Entity (drop-down menu) N
- Entity Type (conditional drop-down menu - must select "entity" first) N
- Entity Name (search box) N
- Browse by year (links to results, confined to selected year) N
- Pending AO Requests (links to a list of the pending requests) N

**Comment by nickykrause** [comment]
Response from Cheryl:

>Hi Nicky,

> As promised here are the results of our "gut check" on AO functionalities used.  I am including my own responses here along with those of the 4 Policy staff members who responded.   At the end of each line item I've noted how many of the five responded that they use that function.  

> Please let me know if we can provide any further information at this point.


>Thanks, 
>Cheryl

>   *   AO number (search box) - 5 of 5
  *   AO Name (search box)  4 of 5
  *   AO document type (checklist)
     *   Final Opinion 2 of 5
     *   AO Request, Supplemental Material, and Extensions of Time  1 of 5
     *   Draft Documents  2 of 5
     *   Votes
     *   Withdrawal of Request
     *   Comments and ex parte communications
     *   Commissioner Statements  2 of 5
     *   All categories  1 of 5
     *   AO Request Date (date range)
  *   AO Issued Date (date range)  2 of 5
  *   Entity (drop-down menu)  
     *   Requestor
     *   Counsel/Representattive*   Commenter  
  *   Entity Type (conditional drop-down menu)  2 of 5
     *   Federal candidate/candidate committee/officeholder
     *   Publicly funded candidates/committees
     *   Party committees, national
     *   Party committees, state or local
     *   Nonconnected political committee
     *   Separate segregated fund
     *   Labor Organization
     *   Trade Organization
     *   Membership Organization, Cooperative, Corporation W/O Capital Stock
     *   Corporation (including LLCs electing corporate status)
     *   Partnership (including LLCs electing corporate status)
     *   Governmental entity
     *   Individual  1 of 5
     *   Research/Public Interest/Educational Institution [for commenters only]
     *   Law firm [for commenters or counsel/representative only]
     *   Other
  *   Entity Name (search box) 3 of 5
  *   Browse by year (links to results, confined to selected year)  4 of 5
  *   Pending AO Requests (links to a list of the pending requests) 3 of 5

**Comment by nickykrause** [comment]
Of the options we don't already have, it looks like the following are three most popular:

1. **Year** (confine results to AOs from a specific year - seems to be the year of issue)
2. **Pending AO requests** (show/hide pending AO requests)
3. **Entity name** (search field)
    - Here is a [detailed description from fec.gov of how this field currently works](http://saos.fec.gov/saos/tips.html#_Entity_Name_Search)

**Comment by porta-antiporta** [comment]
Some food for thought @nickykrause:  Is prioritization of a field sufficient to be considered refinement?

This came into mind when I saw **AO Name** and **AO Number**. We already prioritize **AO Number**.  i.e. if someone enters `2015-12` it puts that AO to the top of the list.  However, we see other results.

For refinement, does that mean we need to *only* show `2015-12` AO?  Or is the current functionality good enough?

**Comment by nickykrause** [comment]
**I spoke with Ed Mullen and Jen this morning. Summary of that:**

Learned that Ed's previous mock-ups of possible AO filters were not informed by specific, pointed research into AO filtering needs, but rather by a general sense of user needs (derived from the larger body of user interviews and interactions), as well as by a look at the existing AO filters on fec.gov.

Ed also reinforced the idea that users will want to search Final Opinions primarily, but that it is important not to discount the need for users to search by other kinds of docs. He explained that while _some users_ do seem interested solely in the final opinion, there are some quite "advanced" users who do indeed have an occasionally need to search other doc types. For this reason, his mockups included doc type filters. 

Finally, Ed advised that we not try to anticipate _all_ of the user needs, because it will be very difficult for users to speculate about what they _might_ want from this kind of advanced filtering, but rather to implement something basic/straightforward and proceed to iterate with testing.

---

**After reflecting on all that, and the other investigations outlined above, my initial thoughts are to design the following filters:**

- Search terms (text)
- Document type (checkboxes)
- Document issue date (range)
- Entity name (text) - this one is questionable...

Here is a use case to help think through the filters in context:
1. User access Legal Resources, does a universal search for the phrase "foreign national"
2. User receives results page, organized by resource type.
3. User selects option to view all AO results
4. User is taken to AO results page, where:
    - The "final opinion" document type checkbox is already enabled
    - The text phrase "foreign national" is already enabled as a filter
5. User could then add:
   - A document issue date range, which would narrow their results to show only documents that had been issued within that range
   - Another document type, which would expand their results to show where "foreign national" appears in Final Opinions _as well as_ whatever other doc type, so long as those docs were issued within the date range.
   - An "entity name" text filter, which would narrow their results to show only those AOs where all the above filters are true AND the name of some entity associated with the AO (requestor, counsel, or commenter) contains those terms.

The entity name one probably needs some more thinking. 

Also, I have questions about how filtering interferes with the idea of "sorting" results by relevance. 

I am running into a meeting, though, so I am linking to the doc where I've been thinking about this: 
https://docs.google.com/drawings/d/1jFlj2EKWweF1QcVGDH2n4_xsw4_jxz58VIFqaK0cmvQ/edit

**Comment by nickykrause** [comment]
(cc: @adrianwebb)
 
After some more thinking and refinement, this document is now updated with a summary of the current interaction design thinking on AO filters, with a few questions remaining: https://docs.google.com/drawings/d/1jFlj2EKWweF1QcVGDH2n4_xsw4_jxz58VIFqaK0cmvQ/edit

The questions included there are specifically for @anthonygarvan, and it may be difficult to wade through them asynchronously. Tony, I know you're really busy, so I am happy to set up time for Tues am before my flight, if meeting would be easiest. After that, I will be onsite in DC (with Jen) for the week, with limited availability.

@jenniferthibault has already started some thinking on how the existing design patterns from the data side would be applied to the proposed AO filters. She will be documenting the creation of those mockups in a separate issue: https://github.com/18F/openFEC-web-app/issues/1619#issuecomment-252073418

**Comment by jenniferthibault** [comment]
Closed in favor of moving work to https://github.com/18F/openFEC-web-app/issues/1619

**Comment by adrianwebb** [comment]
Moving discussion to: https://github.com/18F/openFEC-web-app/issues/1619
