### ISSUE TITLE
Ramp up for Tadhg

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#278]
@anthonygarvan to pair with Tadhg to give an overview of the universal search stack

Ramp up on:
- [ ] Overview of all the repos/projects (web app, cms, etc)
- [ ] openFEC - Universal search in API
  - [ ] Daily celery tasks
- [ ] fec-eregs

**Comment by porta-antiporta** [comment]
Could look to reuse the onboarding that was done for Jon.  @LindsayYoung to try to find it.
Include @vrajmohan as well.

**Comment by adrianwebb** [comment]
Tadhg should be starting Monday 10/17

**Comment by adrianwebb** [comment]
Start prepping some introductory material for Tadhg when he starts

**Comment by adrianwebb** [comment]
Some links from Carlo to incorporate into material:

Git Flow Cheat Sheet: http://danielkummer.github.io/git-flow-cheatsheet/
FEC Wiki: https://github.com/18F/fec/wiki
OpenFEC Wiki: https://github.com/18F/openFEC/wiki
OpenFEC README: https://github.com/18F/openFEC/blob/develop/README.md

**Comment by adrianwebb** [comment]
FEC repo: https://github.com/18F/FEC

**Comment by adrianwebb** [comment]
Generate a central documentation structure for new team members. (18F, FEC, and contractors)

**Comment by adrianwebb** [comment]
@anthonygarvan: Curious if you ever got to pair with @tadhg-ohiggins to give him an overview of the legal applications?

**Comment by adrianwebb** [comment]
Closing this issue since he has been on the project for a while.
