### ISSUE TITLE
When no statutes or regulations are found, quite a bit of real estate is taken up and user thinks there is no results at all

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#279]
When a search results in no hits for `Statutes` and `Regulations` each one of those sections displays the `No Results Found` message.  These messages take up quite a bit of space on the screen and is exacerbated on mobile.

https://fec-dev-proxy.18f.gov/data/legal/search/?search_type=all&search=2015-02

This can lead the user to think there are no results while in fact there are.  

Need to design a better mechanism of showing no hits for a particular asset type but still let the user know that there are still results.

The current error message provides the user a way to submit feedback or look on fec.gov.  Is that still needed?

Goal of this story:
- [ ] Update design for no results for all assets
- [ ] Validate that new design is technically feasible

Note that this was something that the commissioners noted as well.  One of the suggestions in that session was to order the results by number of hits rather than in a hardcoded order.

**Comment by porta-antiporta** [comment]
@emileighoutlaw @jenniferthibault @nickykrause to discuss this issue prior to sprint planning.

**Comment by porta-antiporta** [comment]
@porta-antiporta @adriwanwebb reminder to create an implementation task and tie to this story.

**Comment by jenniferthibault** [comment]
Our first thought is to try reordering the results based on the number returned in each category. That would make this a light design lift, as long as it's technically feasible, then we'd want to retest it to validate.

**Comment by vrajmohan** [comment]
Clarifying, the solution is to order the categories in _descending order_ of the number of results in categories, with ties broken up in the order Statutes before Regulations before Advisory Opinions before Enforcement Matters? Also, we would order the left-hand side navigation in the same order?

**Comment by jenniferthibault** [comment]
YES! Thank you for the attention to detail here Vraj, that's precisely what I was picturing but didn't articulate. Also confirmed with Nicky and Emileigh in person.

**Comment by vrajmohan** [comment]
After further discussion, it was decided that we would preserve the order "Statutes, Regulations, Advisory Opinions, Enforcement Matters" but drop categories with 0 results to the bottom.
