### ISSUE TITLE
Get feedback from FEC on MURs

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-eregs#289]
In order to release MURs we need to get feedback from FEC enforcement folks. 

This is high priority and necessary for release!
- [x] Create structured feedback document
- [x] Share with FEC
- [ ] Implement changes, as necessary

Adrian will be taking charge of this issue and consulting with Porta as necessary. 

cc @amykort and @wluoFEC for visibility.

**Comment by AmyKort** [comment]
Thank you!

**Comment by porta-antiporta** [comment]
My thoughts are to have the users validate the usability/accuracy of what we support.  Also, somehow set the expectation that not all fields that may be in EQS are in our implementation and ask what should be included next).  With that in mind:

- [ ] Were you able to search for MURs?
- [ ] Were the MURs currently returned what you expected?
- [ ] Is the following on the current canonical page correct:
    - [ ] Summary
    - [ ] Disposition
    - [ ] Documents
    - [ ] Participants
-  [ ] Is the following on the archived canonical page correct:
    - [ ] Summary
    - [ ] Participants
    - [ ] Able to download the document
- [ ] Are the mapping from title 2 USC to title 52 USC correct?
- [ ] What other fields/functions that you currently use are not yet present?

**Comment by AmyKort** [comment]
This looks good to me. Thanks!

**Comment by emileighoutlaw** [comment]
Woohoo for a quick turnaround! Does this look good to you @adrianwebb? If so, I can make it into an email or Word Document (which would you prefer @AmyKort?) to pass around to the appropriate reviewers.

**Comment by AmyKort** [comment]
Email would be awesome!

**Comment by emileighoutlaw** [comment]
Does this look good to you @adrianwebb ?

**Comment by emileighoutlaw** [comment]
@adrianwebb I'm just realizing we still haven't sent this out. Does this look good to you?

**Comment by AmyKort** [comment]
Oh . . . um . . . I already sent that out.

**Comment by emileighoutlaw** [comment]
Oh great! Perfect, @AmyKort! I was just panicked that we hadn't done this yet. ☺️

**Comment by jenniferthibault** [comment]
This issue is long overdue for closing: Amy graciously collected and organized the feedback into a [Google Doc](https://docs.google.com/document/d/1eVFGVEDJEOESyjOptWO58uYJkg7NB26xF6rK9fCQE6E/edit#heading=h.mwqzr1upfz4f) for us. 

Since changes required for release are being tracked through Epics, this seems like it can be closed.
