### ISSUE TITLE
MUR canonical page lists counsel as a respondent

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#291]
On the MUR canonical page, attorneys representing the respondent are listed as respondents as well.  

https://fec-stage-proxy.18f.gov/data/legal/matter-under-review/6299/ - Kelner, Robert K
https://fec-stage-proxy.18f.gov/data/legal/matter-under-review/6186/ - Churchwell, Steve

Both the above are listed as respondents in the Summary section.  They should not be.

They are correctly identified as Respondent's Counsel at the bottom of the canonical page (Participants table).  So we seem to have the information required to NOT display them as respondents under the Summary section.

**Comment by vrajmohan** [comment]
In this context, should a participant with role "Previous Respondent" be listed as a Respondent in the summary?

**Comment by porta-antiporta** [comment]
@vrajmohan When we had a larger meeting with @adrianwebb @anthonygarvan @jenniferthibault @nickykrause one of the things that surfaced was that there are a lot more `participant types` than what is reflected in the mockups.   So a follow up was to ask FEC for more of a description for each of those types.

For the purposes of this story, the most pressing need is to remove `counsel` from being listed under `summary respondents`.  So would recommend we scope this story to that isolated change.  And then open a new one re: `previous respondent` when we get that description from the FEC.

All this would of course need the 👍 from @adrianwebb.

**Comment by adrianwebb** [comment]
Sounds good to me.
