### ISSUE TITLE
Investigate and fix cause of eRegulations platform crash when hit with search indexer bots

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-eregs#292]
Every few weeks we have the issue where the eregs site crashes due to search index traffic (last time it was Yahoo Slurp).  A simple restart of the web server usually brings the site back up, but we need to find out what is causing the site to go down in the first place.

We need to load test and replicate the issue in staging, so we can figure out what is going on.

**Comment by tadhg-ohiggins** [comment]
It appears that this https://github.com/18F/fec-eregs/pull/280 has not been pushed to production yet. I'm not yet familiar enough with git-flow yet to know when that's supposed to happen, or if it requires a specific merge as opposed to getting pulled in from `develop` on a regular schedule.

**Comment by tadhg-ohiggins** [comment]
The version of `fec-eregs` with gunicorn has been pushed to production as this release https://github.com/18F/fec-eregs/releases/tag/public-beta-20161027

**Comment by noahmanger** [comment]
Can this issue be closed with the previously mentioned release?

**Comment by tadhg-ohiggins** [comment]
Only if we think the hypothesis that the switch to gunicorn has fixed it. As far as I know the only way we'll determine that the crash bug is fixed is if the production site doesn't crash for several weeks (which isn't an ideal criterion).
