### ISSUE TITLE
Investigate incorporating the issue tags from Law Manager to MUR search/refinement

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-eregs#295]
Look into what it would take to get Law Manager tags integrated into the MUR search.

Based on a comment by @jenniferthibault this would likely require a OGC sign-off.

**Comment by jenniferthibault** [comment]
I split the citations into a separate issue: https://github.com/18F/fec-eregs/issues/303

So narrowing this issue down to only focus on investigation into somehow incorporating the tags from Law Manager in users' search or refinement activities. This seems to overlap with looking into other additional data sources for MURs in https://github.com/18F/fec-eregs/issues/294
