### ISSUE TITLE
Ensure production quality ElasticSearch deployment

### ISSUE THREAD

**Issue by vrajmohan** [18F/fec-eregs#306]
We need to ensure that production quality is being delivered with the ElasticSearch deployment, dealing with specific issues like:
1. Backup of indexes
2. Ensuring high availability
3. Monitoring of logs for errors
4. Migration to ElasticSearch 2.x or 5.x - see https://www.elastic.co/support/eol. This issue may also be covered under https://github.com/18F/fec-eregs/issues/305

Due to lack of familiarity with ElasticSearch, I may be missing other issues that need to be covered; please feel free to add them.

**Comment by adrianwebb** [comment]
This sounds great to me.

**Comment by noahmanger** [comment]
You did this, right @vrajmohan ? Was there anything else you needed to do?

**Comment by vrajmohan** [comment]
This is not done. I have merely tested with Elasticsearch 2.x, and found that we are good with just a library change.
