### ISSUE TITLE
Investigate multiple legal documents of the same type with identical "no" field values

### ISSUE THREAD

**Issue by vrajmohan** [18F/fec-eregs#309]
When we search for a specific legal document by the `no` field, we are getting multiple hits and (somewhat arbitrarily) returning the 1st hit. For current MURs with the specific MUR number 6198, we found 2 docs in the index one with an id of `mur_6198` and another with a suspicious-looking id of `AVg_5xK3gmBsr3k8i1Mn`. In the case of AOs, the problem is worse: 4 regular-looking ids and 6 suspicious-looking ids for `advisory-opinions/2012-01/`. We need to identify the root cause as well as ensure that we return the correct _version_.

**Comment by vrajmohan** [comment]
To reproduce, use `cf-ssh` and then execute:
```
curl http://<<elasticsearch-uri>>/docs/murs/_search -d '
{"query": {
        "bool": {
             "must": {
                     "term": { "no": "6198"}}}},
"fields": "_id"
}'
```
If there's more than 1 hit, it indicates a problem.

**Comment by vrajmohan** [comment]
A data point - the situation mentioned in the summary is from the `dev` environment:
- MUR 6198 - 1 normal id and 1 'Avg_' id
- AO 2012-01 - 4 normal ids and 6 'Av..' ids

In the `stage` env, it is:
- MUR 6198 - 0 normal ids, 1 'Avg_' id
- AO 2012-01 - 4 normal ids and 6 'Av..' ids

`load_current_murs` was run on `dev` and not on `stage`. @anthonygarvan : Before I disturb the data any further, does this data point give you any clue?

**Comment by vrajmohan** [comment]
Culprit identified - I ran the `enable_stemming` task on dev - the 1 normal id for MUR 6198 and the 4 normal ids for AO 2012-01 all flipped to the system-generated style - `AVhUH-iIgmBsr3k8oIYl`, etc. I am going to run load_current_murs to see whether a new normal id is now generated for MUR 6198.

**Comment by vrajmohan** [comment]
I found that it is much simpler to use http://elasticsearch-py.readthedocs.io/en/1.9.0/helpers.html#reindex for reindexing after enabling stemming. I'll create a PR with that change. We will also need to clean up (remove) the duplicate documents.

**Comment by vrajmohan** [comment]
Also noticed that the duplicate documents naturally lead to duplicate hits in search results as shown below:

<img width="966" alt="screen shot 2016-11-12 at 2 26 47 pm" src="https://cloud.githubusercontent.com/assets/2066204/20240385/d9f9764a-a8e4-11e6-8c64-c3e007146484.png">

**Comment by vrajmohan** [comment]
The duplication for current MURs has been fixed through https://github.com/18F/openFEC/issues/2053. Duplication for current MURs is a non-issue because they have all been deleted through https://github.com/18F/openFEC/issues/2053.

We need to remove the duplication for other document types like AOs.
IIANM, nothing needs to be done for statutes and regulations. Correct, @anthonygarvan ?

**Comment by vrajmohan** [comment]
Given that stemming has already been enabled for the `docs` index in all the environments and that `enable_stemming` has a bug, I would choose to remove that task and create a separate task `create_docs_index` to create new indexes with the right mappings. @anthonygarvan, does that make sense? Alternatively, I can submit a PR for fixing the `enable_stemming` task.

**Comment by noahmanger** [comment]
This was resolved and shipped.
