### ISSUE TITLE
Missing sections 300.1 and 300.2

### ISSUE THREAD

**Issue by cmc333333** [18F/fec-eregs#323]
While working on some unrelated code detangling (eregs/regulations-parser#336), I found my integration tests were failing. It turned out that my changes had fixed a problem where sections before the first subpart weren't getting included in the final tree. Unfortunately, FEC's 300.1 and 300.2 fit this category, meaning they aren't being shown in the UI: https://beta.fec.gov/regulations/300

That problem should get fixed with that PR (still in progress), but let me know if there's a more urgent need as there are more direct solutions.

**Comment by noahmanger** [comment]
Thanks for raising this @cmc333333 . We can wait until that PR is merged.
