### ISSUE TITLE
Refresh mechanism for Legal databases

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-eregs#324]
We need to have Salient set up a refresh mechanism for each of the legal data sources. I don't know if that should be a nightly update or on demand or perhaps an hourly check.  The nature of the data is that it isn't updated on a daily basis but when it is update it probably shouldn't wait overnight to refresh.

Any thoughts?
@LindsayYoung @ccostino @vrajmohan @anthonygarvan @adrianwebb

**Comment by noahmanger** [comment]
Closing in favor of https://github.com/18F/openFEC/issues/2220
