### ISSUE TITLE
Remove disposition from summary on MUR canonical pages

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-eregs#325]
### Background

There is [a known issue for the MUR canonical page](https://github.com/18F/fec-eregs/issues/294), in which we have found that the `Disposition` information included in the `Summary` of a MUR is not useful for users. 

Here is an example of the `Disposition`:
<img width="511" alt="disposition" src="https://cloud.githubusercontent.com/assets/1450173/21504176/382801e0-cc22-11e6-8ed5-a65074e28d26.png">

This information is not useful for several reasons, which are summarized in the original issue. The main problem is that we are not pulling the `Disposition` information from the ideal source. Unfortunately, however, we have not yet been able to determine how to proceed with a better, alternative source.

While we wait for the sourcing issue to be resolved, we'd like to remove the `Disposition` information from the `Summary`, so that it does not provide a needless distraction to  users during testing, and so that it allows the users to scroll more quickly and easily to the information further down the page, which _is_ useful to them. 

### Completion critera

- [ ] `Disposition` information has been removed from the `Summary` for MURs

**Comment by nickykrause** [comment]
During our call, I believe we had some trouble identifying examples of MURs where the `Disposition` within the `Summary` was quite long. Here is one of those examples: https://beta.fec.gov/data/legal/matter-under-review/2314/

**Comment by nickykrause** [comment]
One more thing for clarity: All of that info that we are currently including in the `Disposition` section of the `Summary` seems to come from what is currently the `Votes` section of a MUR in EQS:

![mur_votes](https://cloud.githubusercontent.com/assets/1450173/21526052/10404730-cce7-11e6-973d-cc1e5d47c59b.png)

**Comment by nickykrause** [comment]
Update here: Over in #326 , we started investigating other ways to display this information (possibly as a Votes section, rather than as a part of the Summary). 

@noahmanger Unless you disagree, I think we could close this issue in favor of #326?

**Comment by noahmanger** [comment]
Works for me!
