### ISSUE TITLE
Investigate using plain-language summaries from Weekly Digests for AOs/MURs

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-eregs#327]
### What this issue is about
Find out from the FEC if we can pull plain-language summaries of AOs and MURs from the Weekly Digests for use on the AO and MUR canonical pages. Gain an understanding of what kind of a technical lift it would take to implement the plain-language summaries.

Completion criteria:
- [x] An answer from the FEC about whether or not we can do this
- [x] An understanding of what kind of a technical lift this would be to implement

### Background
Over in https://github.com/18F/fec-eregs/issues/294, we talked about ways to improve the `Summary` section of a MUR. Eventually, as a part of that conversation, we realized that the problematic information in the `Disposition` section of the `Summary` actually corresponded to the `Votes` section in EQS. We are investigating ways to resolve the `Votes` information over in https://github.com/18F/fec-eregs/issues/326. 

However, we are still left with the question of how to handle the `Summary` for MURs. On that note, another thing we realized in https://github.com/18F/fec-eregs/issues/294 was that the original plan, from a design standpoint, was to include a plain-language `Summary` of each MUR, drawn from somewhere other than EQS. We talked about drawing it from the Weekly Digests, but that plan eventually stalled. Jen summarizes that here:

> I spoke with Amy on Nov 2nd about this over Slack— The FEC does have MUR summaries from the press office's weekly digests that cover every MUR--even ones from the archive. This is commission-approved language, which is a plus. It's all kept in a Word document right now, which is a minus.
> the beta site has scraped Weekly Digests for all MURs from the 2000's, but not before. So we'd still need to get this data from everything before 2000
> We left off at this assessment, and Amy was going to think about how to best approach the FEC's office of General Counsel about this. I don't believe it's moved, because there have been other priorities, and I'd want to wait to nudge it until this task comes closer to being assigned a sprint again. 

Fast forward to last sprint, and this same question about plain-language summaries on canonical pages has come up again, but now in regard to AOs. This happened over in https://github.com/18F/openFEC-web-app/issues/1736. As Jen explained, 

>the [original AO design from Ed Mullen](https://gsa.invisionapp.com/share/AR7U3Y662#/167711253_AO_Index) does have longer content in the summary section [of the AO] that would be pulled from the FEC Record. Digging deeper, I learned a while ago that the preference is to actually pull this summary data from the Weekly Digests (Just like the MUR disposition info) 
<img width="1090" alt="screen shot 2016-12-28 at 7 42 08 pm" src="https://cloud.githubusercontent.com/assets/11636908/21534518/673ae6cc-cd36-11e6-8643-55f0ef709af2.png">

This issue involves picking up both of these threads -- for both AOs and MURs -- and deciding if we can/should attempt to implement this.

**Comment by noahmanger** [comment]
As discussed in this week's grooming meeting, we're going to move forward with this. I made two separate issues for implementing for [AOs](https://github.com/18F/openFEC/issues/2153) and [MURs](https://github.com/18F/openFEC/issues/2155).
