### ISSUE TITLE
Upgrade eregs 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-eregs#370]
Updating core dependencies will update django

Instructions via @cmc333333 

upgrade your `regulations` and `regcore` dependencies. We’re on 8.4.1 and 4.2.0 respectively. Here are the release notes:
https://github.com/eregs/regulations-site/releases
https://github.com/eregs/regulations-core/releases

That should allow you to run Python 3 and with Django 1.11 as we do on ATF. (edited)
Only gotchas I can think of would be around style overrides, which will need to be tested manually. I think you could definitely merge fec-eregs and openFEC; fec-eregs is just glue code and theme overrides, iirc

**Comment by AmyKort** [comment]
This will resolve issue identified in Security Alert: Django for fec-eregs #362

Need to upgrade to the version that will fix this XSS traceback security issue.
https://gemnasium.com/github.com/18F/fec-eregs

**Comment by patphongs** [comment]
These were the commands that were run locally to get eregs to run on my machine:
