### ISSUE TITLE
Usability Testing - Blanket validation of Design Concept

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#46]
We have presented several mockups in our demos and used the feedback there to implement code.
Now that we have a healthy user experience designed, we want to get into a cadence of performing usability testing to validate the designs before implementing.

In this sprint we want to test:

* Browsing
* AO canonical landing page

**Comment by edmullen** [comment]
Each week of the sprint we have conducted usability tests.

**Week 1** conducted by @emileighoutlaw: [Script & Notes](https://docs.google.com/a/gsa.gov/document/d/1wDDMwGgvBo_qHBvNNcgyTz4Ub-yHjvgGR0XeBozKTvI/edit?usp=sharing)
**Week 2** conducted by @onezerojeremy: [Script](https://drive.google.com/open?id=1zhUkMAeLGNFX0Sz1r6H2MOGQj5MNjBaDpMORsmaiTBE) | [Notes](https://app.mural.ly/t/gsa6/m/gsa6/1461202199851)
**Week 3** conducted by @onezerojeremy: [Task 1 Issue](https://github.com/18F/fec-eregs/issues/70) | [Task 2 Issue](https://github.com/18F/fec-eregs/issues/72) | [Murally notes](https://app.mural.ly/t/gsa6/m/gsa6/1461805816840)
   
**A few notes**

Browsing seemed to not cause trouble for the test users. The basic navigability seems sufficient at this point. People understood the functionality of the initial search input. They were able to browse to the Regs and AOs sections from the homepage. The section name, _legal resources_, was clear except when the user was looking for legal guidance related to Registration & Reporting. The section name can be changed with few implications if need be. This issue also reinforces the known user need of creating interconnections across the site and is additional evidence an integrated site-wide search may be helpful in the future.

The Advisory Opinion canonical page was tested in weeks 1 and 3, and revised in between. The page was seen as clear and straightforward. When the FEC Record summary was included, it was seen as helpful information in understanding the topic of the AO.


**Issues based on conclusions of this research:** #68 #71 #73 #74 #76 #83 and fec-style [#330](https://github.com/18F/fec-style/issues/330)
