### ISSUE TITLE
Design Spike - Merge eregs into beta.fec

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#47]
Lets discuss this during planning.

In the next few sprints, we want to have eregs visible from beta.fec.gov so that 
a) we will be able to release it to the public
b) we are able to search across eregs and other legal resources

To the untrained user, it should feel as if they are just viewing beta.fec.

However, currently eregs is a separate stack of assets from a separate instance of elastic search backend to a separate app.  Integrating this into beta.fec is not a trivial task.

Does it make sense for us to design spike the way we will merge the two?  Or do we start the work (but need guidance on how to split it up into manageable stories)

Things to keep in mind
* eregs search vs. integrated search : do we keep both or just support integrated search?
 * if we just support integrated search, will that preclude us from supporting historical diff searches in the future.
* iFrame?
* Keep separate backends
* etc etc

**Comment by porta-antiporta** [comment]
@anthonygarvan @adborden @tadhg-ohiggins @edmullen @annalee 

Porta to set up a meeting for front end and back end

Tony, Tadhg, Annalee - Backend
Aaron, Ed - Frontend

**Comment by edmullen** [comment]
I'll participate.

**Comment by edmullen** [comment]
I'll participate.

**Comment by adborden** [comment]
@porta-antiporta can you also keep me in the loop for the backend conversation?

**Comment by porta-antiporta** [comment]
Sure thing @adborden

**Comment by adborden** [comment]
I had done a little research a while back on [how might we integrate the two apps under a common front end](https://gist.github.com/adborden/515015cf761cbff12ea31929fbdfa5a7). The evaluation I did was hardly thorough and wasn't really peer-reviewed, so let me know if there's areas I missed or a direction we left unexplored but should follow up on. Please comment on the gist for anything notes related, but in this issue for next steps/direction. Here's what I think we should do for next steps in terms of integrating the front end:

1. Abandon the iframe strategy.
1. Add cf map-route for fec-web-dev to eregs to get the same-domain feel.
1. Investigate how to better handle difference of global font-size in eregs and fec-style.
1. Start evaluating the complexity involved in implementing the critical FEC UI
 components on eregs.

I think the most straight forward approach is to add the FEC UI components to
eregs and host them as separate apps. It looks like cloud.gov supports map-route, so
we can get eregs under the betaFEC domain by adding a route that proxies to
eregs as a secondary enhancement.

Adding FEC components is doable, but not cheap. I suggest we look at the
components on a case by case basis and only integrate the components that are
considered critical for the integration to "feel right". That list of components
might be:

- US gov beta disclaimer
- masthead
- site nav
- sub header

And specifically not:

- glossary
- footer

As much as possible, I would like to keep our solutions supported by upstream.
For example, integrating the FEC masthead requires having a larger, static header
(not fixed) in eregs. I'd like upstream to support that as an option through
build time configuration (built by us, of course).

What do you folks think?

**Comment by adborden** [comment]
Some conversation here on related routing changes https://github.com/18F/openFEC-web-app/issues/1193
