### ISSUE TITLE
Implement all AOs returned page

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#52]
Currently we display the combined search page which only displays the top 10 results.

Let's implement the next page where the user has clicked on display all results for AOs.

**Comment by porta-antiporta** [comment]
Duplicate of #48 and #62

**Comment by porta-antiporta** [comment]
Actually this is _not_ a duplicate of the above stories.  This is the new page displaying all the AOs.

**Comment by adborden** [comment]
This is the [related screen](https://gsa.invisionapp.com/share/5T6WZK1X3#/screens/145835127) I believe.

**Comment by adborden** [comment]
WIP https://fec-web-adborden.18f.gov/legal/advisory-opinions/?search=document

**Comment by adborden** [comment]
Also considering inspiration from https://github.com/18F/fec-style/issues/318

cc @edmullen

**Comment by edmullen** [comment]
This is the current version of this page: https://invis.io/9Q710V45R#/152289926_AO_Search 

cc @adborden

**Comment by edmullen** [comment]
This looks good. Two things stand out:

**[1]** The upper right of the results table don't have the controls usually present on the data side.

![image](https://cloud.githubusercontent.com/assets/2654503/14901926/efd57452-0d65-11e6-9845-43cfc0b50792.png)

(example from data side)

**[2]** There is no margin on the right side.

![image](https://cloud.githubusercontent.com/assets/2654503/14901900/cfd8c406-0d65-11e6-8b0d-58690064d9c2.png)
(example from data side)

**[3]** There is no margin under the table.

![image](https://cloud.githubusercontent.com/assets/2654503/14901991/34759d76-0d66-11e6-91f6-fe5555ceb198.png)
(example from data side)

**Note:** I still see the occasional loading error that's been mentioned were sometimes a search results incorrectly show no results. This is usually resolved by hitting refresh, and it's not specific to this page. Seems like a site-wide issue.

![image](https://cloud.githubusercontent.com/assets/2654503/14902073/bdd2d728-0d66-11e6-9207-23a597fbd7f3.png)

**Comment by adborden** [comment]
Thanks @edmullen I'll address those UI comments.

> **Note**: I still see the occasional loading error that's been mentioned were sometimes a search results incorrectly show no results. This is usually resolved by hitting refresh, and it's not specific to this page. Seems like a site-wide issue.

Yeah, I see it, too. we haven't been able to track that down yet. I was able to find the related stack trace, tracking it in https://github.com/18F/fec-eregs/issues/80.
