### ISSUE TITLE
Stand up feature branch environment

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#53]

**Comment by anthonygarvan** [comment]
(commenting to be added as a participant)

**Comment by anthonygarvan** [comment]
api is upon `feature` space.

**Comment by adborden** [comment]
https://fec-feature-proxy.18f.gov

In general, the individual apps can be deployed with `invoke deploy --space feature` or `cf target -s feature && cf push -f manifest_feature.yml`

**Comment by adborden** [comment]
Meh, I'll leave it open until the PRs are closed.

**Comment by adborden** [comment]
https://github.com/18F/openFEC-web-app/pull/1197
https://github.com/18F/fec-proxy/pull/7
