### ISSUE TITLE
Integrate findings from usability testing 

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#54]

**Comment by edmullen** [comment]
Issues related to integrating findings from this pass of research:

- [#68 Integrate content area into Legal landing page](https://github.com/18F/fec-eregs/issues/68)
- [#71 Develop the AO canonical page](https://github.com/18F/fec-eregs/issues/71)
- [#74 Update the all sources search results "view more" styles](https://github.com/18F/fec-eregs/issues/74)
- [#76 Add "More hits" and canonical AO link to the AO section in the universal legal search](https://github.com/18F/fec-eregs/issues/76)
