### ISSUE TITLE
Heading instead of text

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#6]
100.2 (d)d. Runoff election. Runoff election  means the election which meets either of the following conditions:

https://fec-eregs.apps.cloud.gov/100-2/2015-annual-100#100-2-d

![heading-instead-of-text](https://cloud.githubusercontent.com/assets/11817734/13259784/e60956ea-da26-11e5-9c20-f76d2cc5c318.png)

**Comment by PaulClark2** [comment]
100.2(f) f. Special election. Special election  means an election which is held to fill a vacancy in a Federal office. A special election may be a primary, general, or runoff election, as defined at 11 CFR 100.2 (b), (c) and (d).

https://fec-eregs.apps.cloud.gov/100-2/2015-annual-100#100-2-d

![heading-instead-of-text2](https://cloud.githubusercontent.com/assets/11817734/13259868/408d67d2-da27-11e5-9783-6cc6f0e5d131.png)

**Comment by cmc333333** [comment]
@PaulClark2 these are intentional -- we refer to them as "keyterms" in eRegs, but they are part of the original regulation

**Comment by PaulClark2** [comment]
@cmc333333 Ok,  I can understand "Special election" being bold and in a larger font once but it doesn't make sense for it to be bold and in a larger font twice.  The second occurrence of "Special election" is the beginning a sentence.

@amykort

**Comment by porta-antiporta** [comment]
https://trello.com/c/frzPwggj/21-fec-eregs-heading-instead-of-text

(not ideal until i find a way to sync comments between trello and GH)
