### ISSUE TITLE
Load AO PDFs into S3 and link to them

### ISSUE THREAD

**Issue by anthonygarvan** [18F/fec-eregs#60]
Currently, we are linking to the PDFs hosted on fec.gov. We should port the AOs into cloud.gov and update links in elasticsearch:

- [ ] Get binary data out of Oracle into file
- [ ] Add S3 write API (/load/legalfile/)
- [ ] Write shipper code to post file to /load/legalfile/

**Comment by anthonygarvan** [comment]
@porta-antiporta this is kind of a biggish task, maybe split into 2 cards? One for the refactor and another for the S3 work?

**Comment by porta-antiporta** [comment]
@anthonygarvan what makes sense to you makes sense to me.  
Story 1 : Move to fec-shipper

- [ ] - Get Oracle running on MacOS. I'm over the Oracle VM.
- [ ] -  Connect to Oracle with pyodbc
- [ ] -  Decide on maintainable solution for code execution
- [ ] -  Implement AO shipping code in fec-shipper repo

Story 2: Load into S3

- [ ] Get binary data out of Oracle into file
- [ ]  Add S3 write API (/load/legalfile/)
- [ ]  Write shipper code to post file to /load/legalfile/
