### ISSUE TITLE
Update AO Search UI to use new API functionality

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#62]
As part of https://github.com/18F/openFEC/issues/1623 the API now supports enhanced fucntionality that can be reflected in the UI.

Notably:
- [x] Confirm that ranking is now using default proximity search
- [x] Update snippets using <highlight> data returned
- [x] Update UI to display total number of results in (10 of X)
- [x] Update links of individual documents to bring up the .pdf

**Comment by adborden** [comment]
AFAIK, we still don't have url data for the PDFs, but at least we're getting the fake urls from the API now. That means once we have the pdf urls, we just update the API and the UI will fall in line.
