### ISSUE TITLE
Integrate content area into Legal landing page

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#68]
The content area below the hero can be prepared and integrated into the site. Initial testing showed people able to navigate the area and it closely follows patterns established elsewhere.

@emileighoutlaw We should talk about content needs, which are pretty basic here. 

![legal home - alt alert](https://cloud.githubusercontent.com/assets/2654503/14828984/5e58224a-0bb7-11e6-8492-16e299a14098.png)

For sections not ready, we should fade/deactivate them.

cc @porta @adborden

**Comment by emileighoutlaw** [comment]
Yes! Let's talk about this. It looks like there are a few "legal" definitions of these things floating around, but we'll probably be aiming to get something more plain language written for this page.

**Comment by edmullen** [comment]
One additional aspect. Please remove the "advanced search" link below the field. I don't think that we'll do advanced search at this level any time soon, if ever.

cc @adborden

**Comment by porta-antiporta** [comment]
The approved content text is located at: https://docs.google.com/document/d/1l7PKLJvLmBV0cFONvsIIvee3uDEs2dK_q8JeOqHGAh0/edit#heading=h.qgmk0q45qngu

@anthonygarvan the story during grooming was just to only include the Regulations text.  
Is it a big lift to include the "Coming Soon" text in the above document as well?
