### ISSUE TITLE
Develop the AO canonical page

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#71]
The canonical page for an advisory page is ready for development. The information was generally understood as straight forward in initial testing and I think it's fairly non-controversial.

**Citations:** The mock-up below includes citations on the right, which I do not believe are available. I think we could include the box with grayed-out "Coming" text.

**Audio:** the mock-up below includes a link to the audio from the hearing. This is not ready and should not be included yet.

![image](https://cloud.githubusercontent.com/assets/2654503/14859376/e138892e-0c71-11e6-8b0b-f6a7d1199718.png)

Please note that this version **does not** include the FEC Record summary. That would be an enhancement in the future, so please be aware of it, but don't built it yet. Here's is the current placement of that potential future content: 

![image](https://cloud.githubusercontent.com/assets/2654503/14859327/acf4e7fc-0c71-11e6-8fb7-d0678cd6e2c6.png)

CC @porta-antiporta @adborden

**Comment by adborden** [comment]
Back in May I had started this work. It's all stub data and lives on the [feature/canonical-ao](https://github.com/18F/openFEC-web-app/compare/feature/canonical-ao) branch of `openFEC-web-app`. Hopefully it's useful when someone picks up this story.
![screenshot from 2016-07-07 17-34-43](https://cloud.githubusercontent.com/assets/509703/16674058/389c9c4e-4469-11e6-8369-b4a15bdfa82c.png)

**Comment by porta-antiporta** [comment]
@adborden submitted https://github.com/18F/openFEC-web-app/pull/1524 to address the "Final Opinion" button not pointing to the correct URL
