### ISSUE TITLE
Content: Develop content for the Legal landing page.

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#73]
The Legal landing page will need content created for the two sections that will be present in the near future, Advisory Opinions and Regulations, and _coming_ text for the Enforcement matters. It also could probably use some adjustment to the hero language.

![legal home - ao filing](https://cloud.githubusercontent.com/assets/2654503/14867539/0122a5ec-0c97-11e6-894a-e94aba967fac.png)

The dev page is here. It will be updated as part of #68   

cc @emileighoutlaw @porta-antiporta

**Comment by edmullen** [comment]
Working document: https://docs.google.com/document/d/1l7PKLJvLmBV0cFONvsIIvee3uDEs2dK_q8JeOqHGAh0/edit#

**Comment by edmullen** [comment]
In #86 one user from the FEC info service found the calls-to-action labelled "get started" confusing because you don't start anything. It's just information. So "get started" may be wrong.

**Comment by porta-antiporta** [comment]
commenting so i get updates in email...

**Comment by porta-antiporta** [comment]
@edmullen @emileighoutlaw for the content for Regulations is that 👍 ?  Looking to implement that in this coming sprint so that we can release regulations.

**Comment by edmullen** [comment]
@emileighoutlaw We'll initially be launching with only Regulations and we'll have AOs and Enforcement Matters as coming soon. Could you please look at the copy once again, see if changes are needed, and advise what kind of approvals we'd need for this?

**Comment by emileighoutlaw** [comment]
Hello all! 

@jeanninehunter — I'm tagging you in to take over this content issue moving forward (lots of explanation below; let me know if you have questions). 

### Background
We're writing introductory content for our not-yet-launched `Legal resources` landing page.

### Process
Every piece of content we write needs explicit approval from Amy Kort and Amy Pike before it can be published on the beta site. 
- If either Amy spots anything they think could be point of contention, they'll want to run it through OGC. (If that happens right before a launch, we may have to ask them for some pre-approved language to put on the beta site as placeholder text while we work on getting something better through the Office of General Counsel at FEC. But submitting content to them early for approval helps prevent this from happening.)

### What's happening now
I'm working on the introductory text for `Regulations`. I'll shepherd that through approvals. 

I'm giving you (Jeannine) all the other blurbs to run with and edit/update/change/improve as you see fit!  (woohoo!) This content is for future launches, but we want to get it drafted and approved as quickly as possible, so we aren't blocking other folks on the legal team.

### The deliverable (for Jeannine)
Introductory blurbs for all the different sections that will eventually make up the `Legal resources` home. Those are:
- Advisory opinions 
- Enforcement matters:
    - Matters under review 
    - Alternative dispute resolution
    - Administrative fine program

Here's the document you should work in: https://docs.google.com/document/d/1l7PKLJvLmBV0cFONvsIIvee3uDEs2dK_q8JeOqHGAh0/edit#


Let me know if you have questions, @jeanninehunter.
@edmullen I'll get the ball rolling on getting Regulations text approved.

**Comment by edmullen** [comment]
@emileighoutlaw thanks for the work and guidance on this! I'm going to move this to _done_. 

@jeanninehunter, we'll reach out to you for future versions as needed.

@porta, note the guidance Emileigh provided about clearance requirements. Good info.

**Comment by porta-antiporta** [comment]
@edmullen @emileighoutlaw  Thanks! 🎉   I added it to the  Pls note that my GH username is @porta-antiporta.  Julian Porta has the @-porta username having been on GH for quite some time. 😈 

I added a reference to the approved content to #68

**Comment by edmullen** [comment]
@porta-antiporta Noted  username and modified the previous reference.
