### ISSUE TITLE
Update the all sources search results "view more" styles

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#74]
Update the styles for the legal/all sources search results pages according to @jenniferthibault's [18F/fec-style#318 (comment)](https://github.com/18F/fec-style/issues/318#issuecomment-214396124) guidance.

![legal search results styles](https://cloud.githubusercontent.com/assets/11636908/14789104/13060854-0ad9-11e6-9b4e-d1d1fb431d96.png)

(taken from the comment referenced above)

This is the sibling issue to @jenniferthibault's issue on openFEC-web-app for data: https://github.com/18F/openFEC-web-app/issues/1202

**Comment by porta-antiporta** [comment]
"view all results" and "display all hits" are redundant correct @edmullen ?  i.e. we don't need "display all results" anymore?

**Comment by edmullen** [comment]
@porta-antiporta No, they are not redundant, but the two were getting confused as such. The "view all results" shows the other AOs that were matches for the search. The "display all his" is functionality that currently exists in the live site. It displays additional snippets from the particular AO that have highlighted hits.

But your reading was similar to users and so a revised design had been proposed here to remedy this: https://github.com/18F/fec-eregs/issues/76#issuecomment-215475580

**Comment by noahmanger** [comment]
I believe this has been implemented, so closing.
