### ISSUE TITLE
Adjustable snippet length from legal search API

### ISSUE THREAD

**Issue by adborden** [18F/fec-eregs#75]
If possible, let's configure the legal search snippet text length to be longer. Ideally added as a query parameter to the API so we can play with it.

The current snippet text is too short. We're including all the hits concatenated together, joined with ellipsis. This is misleading because it looks like the text is related but in fact these snippets could be pages apart in the document.

![screenshot from 2016-04-27 18-50-51](https://cloud.githubusercontent.com/assets/509703/14873226/06826010-0ca9-11e6-92d9-783d3395323a.png)

cc @edmullen

**Comment by porta-antiporta** [comment]
@adborden What did you have in mind with the snippet length?.  i.e. How does making the snippet length adjustable aid reduce the confusion around the ellipses joining text that is far apart from each other.

We should revisit the design with @nickykrause.

**Comment by adborden** [comment]
As a searcher, I didn't think the snippet length was long enough to give me enough context to decide whether or not the search results were relevant or not. The short snippet length and the proximity of other snippets joined by the ellipsis implies that these snippets are close together in the document but in fact are not.

My search of "computer" is hardly realistic, though. I haven't had a close eye on the usability tests to see if we have actually tested the readability of our search results yet with legal users.
