### ISSUE TITLE
Design typeahead experience for AOs and Regs

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#78]
Design typeahead experience for AOs and Regs

Considerations :
- [ ] interaction between results -or- advanced query hints
- [ ] Users search for a document type, such as "Advisory Opinions" instead of selecting that doc type from the search scope menu. (Surfaced in usability testing: #86 (comment))

**Comment by porta-antiporta** [comment]
Considerations:
* Typeahead --> interaction between results -or- advanced query hints

**Comment by edmullen** [comment]
Consideration:

- Users search for a document type, such as "Advisory Opinions" instead of selecting that doc type from the search scope menu. (Surfaced in usability testing: https://github.com/18F/fec-eregs/issues/86#issuecomment-218208320)
