### ISSUE TITLE
Inconsistent typeface

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-eregs#8]
https://fec-eregs.apps.cloud.gov/100-14/2015-annual-100#100-14

Compare "B" to "C"

![typeface](https://cloud.githubusercontent.com/assets/11817734/13260063/ef514e50-da27-11e5-9a5e-7ddcaced78b2.png)

**Comment by porta-antiporta** [comment]
https://trello.com/c/d2xPlNkX/23-fec-eregs-inconsistent-typeface

**Comment by tadhg-ohiggins** [comment]
Confirmed fixed in prod: https://fec-eregs.apps.cloud.gov/100-14/2016-annual-100#100-14
