### ISSUE TITLE
Migrate beta.fec UI components to eregs

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#88]
Per our design spike, we will be keeping separate applications to view eregs.
However we want the user to feel they did not leave beta.fec
So we will modify eregs to look just like beta.fec

Links back to beta.fec app 
(https://gsa.invisionapp.com/share/9Q710V45R#/screens/152289960)
- [x] Header
- [x] Legal Resources
- [x] Links back to campaign data and other tabs
- [x] No beta.fec glossary
- [x] Searching _Across_ eregs is NOT in scope

Eregs Content
(https://gsa.invisionapp.com/share/9Q710V45R#/screens/152289960)
- [ ] Bread crumbing
- [ ] Left nav bar
- [ ] Table of contents
- [x] Hide the search across single regulation search icon.

https://gsa.invisionapp.com/share/9Q710V45R#/screens/152289931

Additional header fixes:
- [ ] Sticky scroll, as per https://adborden.github.io/eregs-scroll-prototype/
- [ ] On small breakpoints, the header height should shrink with the FEC masthead
- [ ] Nav menus, mobile and mega menu should display properly

**Comment by anthonygarvan** [comment]
Happy to help out / pair as necessary.

**Comment by porta-antiporta** [comment]
@annalee @anthonygarvan to help on the mobile aspect of things.

**Comment by adborden** [comment]
Added some additional requirements for the header.

**Comment by porta-antiporta** [comment]
@adborden should we close this issue and open new ones for the remaining stuff?
- [ ] Breadcrumbs
- [ ] Mobile - Hamburger menu for navigation of beta.fec doesn't render once on eregs
- [ ] Mobile - Gap between beta fec header and eregs content

**Comment by adborden** [comment]
Done, the new issues are:
https://github.com/18F/fec-eregs/issues/115
https://github.com/18F/fec-eregs/issues/116
https://github.com/18F/fec-eregs/issues/117
https://github.com/18F/fec-eregs/issues/123
https://github.com/18F/fec-eregs/issues/124
