### ISSUE TITLE
Run parser on all regulations to pick up references to U.S.C

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#91]
Currently on 11 CFR 100 includes the linkages to the U.S.C.  We want that to be run on all the remaining regulations

- [x] Run regulations parser on all remaining sections of 11 CFR
- [x] Deploy to dev
- [x] Deploy to staging
- [x] Deploy to prod
- [x] Validate that USC links are launching GPO pdfs

**Comment by porta-antiporta** [comment]
@annalee This did not seem to work in prod:

https://fec-eregs.apps.cloud.gov/regulations/111-8/2015-annual-111#111-8
https://fec-eregs.apps.cloud.gov/regulations/111-1/2015-annual-111#111-1

The citations to USC 52 aren't linked

cc: @tadhg-ohiggins

**Comment by porta-antiporta** [comment]
It is working though on staging.

https://fec-stage-eregs.18f.gov/regulations/111-1/2016-annual-111#111-1

**Comment by tadhg-ohiggins** [comment]
I suspect either the prod codebase is behind staging, or the latest run of regulations-parser against prod used an older version of regulations-parser. (Or nobody ever ran the adjusted -parser against prod, but I recall having done that and verified it.)

**Comment by annalee** [comment]
I ran the same version of the parser against staging and prod (and my copy of regulations-parser is up-to-date). Perhaps I got the prod url wrong? I ran `https://fec-prod-eregs.18f.gov/api --only-latest`

**Comment by adborden** [comment]
@annalee did you use the production credentials? check `cf target -s prod && cf env eregs`. The parser does not complain if it gets a 401.

**Comment by porta-antiporta** [comment]
@adborden to pair with @annalee  to work through CF privilege issues

**Comment by annalee** [comment]
@adborden and I resolved the permissions issue and successfully ran it against staging and prod, but the links to USC are still missing.

**Comment by vrajmohan** [comment]
It appears to be working correctly. E.g., I see working links to USC in:
1. https://fec-prod-eregs.18f.gov/regulations/111-1/2016-annual-111#111-1
2. https://fec-prod-eregs.18f.gov/regulations/111-8/2016-annual-111#111-8-b

**Comment by porta-antiporta** [comment]
let me take another look @vrajmohan.  (app seems down ATM).

**Comment by porta-antiporta** [comment]
Looking at the current functionality.  Citations to USC that are in the `text` of a regulation are correctly linking.  Citations in the title/header of a regulation (ex: https://beta.fec.gov/regulations/111-14/2016-annual-111#111-14) are not linking. 

However, need to investigate whether the core platform intended to link USC citations in regulation headers.

**Comment by vrajmohan** [comment]
Confirmed with @cmc333333 that the core platform does not support this, although it could be implemented. I would like to close this issue. If we need to support links for USC citations in the regulation titles, we should open a separate _enhancement_ issue.
