### ISSUE TITLE
Usability test: Baseline current "validity" of default search results

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-eregs#93]
* Baseline how the quality of AO default ranking is working
* This would likely feed into a story to understand what tuning will need to be done to more appropriately rank default search results.

**Comment by porta-antiporta** [comment]
* Pat will upload logs from legacy search systems to understand what has been searched.
* Conversations with Cheryl and co on current ranking of search results

**Comment by porta-antiporta** [comment]
Based off lack of access to actual SQL of searches, deciding to stop work on this issue until we can have AOs released.

**Comment by edmullen** [comment]
I actually have a plan for this using a Google form and some sample terms that I've culled from a few places. So the actual SQL searches aren't a blocker any more. I'd like to reopen this one if you're ok with it.

This is the form I had planned to share with FEC: https://docs.google.com/a/gsa.gov/forms/d/1HNijon8V9odGox3rLa6fMrqyykiG6S_ukpSoJS64U0k/edit

**Comment by porta-antiporta** [comment]
OK! I'll add the Sprint 15 milestone to it as well.

**Comment by edmullen** [comment]
The form has been sent to FEC. They are going to get an internal approval to proceed.

**Comment by edmullen** [comment]
Adding @Chemsley

**Comment by edmullen** [comment]
@Chemsley and team are going to refine the terms we're using so that the terms represent only one "fact pattern", meaning they are not so broad that there could be dozens of acceptable results depending on the intention of the user.

**Comment by edmullen** [comment]
## Conclusions (IN PROGRESS. MORE WILL BE ADDED.)

We have received XXX responses from our FEC partners. Based on their work, we now have four sample search terms and corresponding results that are considered highly relevant by our subject matter experts. These sample searches can be used to assess the quality of the results from our Advisory Opinion search. Using this information, we will hopefully be able to "tune" our results to produce meaningful suggestions, or investigate why problems may be occurring. 

The following results shown below are in no ranked order. They should all be considered good suggestions for the terms.

### "foreign national subsidiary SSF"

- AO 1998-28 (Bacardi-Martini)
- AO 2009-14 (Mercedes-Benz USA/Sterling)
- AO 1995-15 (Allison Engine PAC)
- AO 2000-17 (Extendicare)
- AO 1992-16 (Nansay Hawaii)

### "electioneering media"

- AO 2004-30 (Citizens United)
- AO 2010-08 (Citizens United)
- AO 2007-20 (XM Radio)
- AO 2005-19 (Inside Track)
- AO 2003-34 (Showtime)

### "text messages"

- AO 2012-30 (Revolution Messaging, LLC)
- AO 2012-31 (AT&T Inc.)
- AO 2012-28 (CTIA - The Wireless Association)
- AO 2012-17 (Red Blue T LLC, ArmourMedia, Inc., and m-Qube, Inc.)
- AO 2012-26 (Cooper for Congress, ArmourMedia, Inc., and m-Qube, Inc.)

### "travel reimbursement"

- AO 2002-05 (Hutchinson)
- AO 1992-34 (Castle for Congress)
- AO 2001-03 (Meeks)
- AO 1994-37 (Schumer)
- AO 1996-34 (Thornberry)
