### ISSUE TITLE
Design assisted search experience

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#94]
_As a person searching legal resources, I should understand the different ways I can structure my search so that I can receive more specific search results._

This is conceived as a simple approach to educating the user on the out-of-the-box operators available in elasticsearch.

**Comment by edmullen** [comment]
@jenniferthibault and I worked through new designs for the search bar on landing pages and cross-type search results page, like the Legal all sources search. That work is found in [/fec-style #370](https://github.com/18F/fec-style/issues/370#issuecomment-225254525)

As a byproduct of that effort, an assisted/advanced search panel was designed. In the example below, the "advanced" link would open the panel, exposing any sources that are part of the search as well as copy about the operators available in elasticsearch.

![advanced all sources search panel](https://cloud.githubusercontent.com/assets/2654503/16098501/4e9aaed6-3321-11e6-86b2-e015e8f0537b.png)

All micro-copy is open to refinement.

I'm not entirely sure if the _hide advanced_ control to close the panel is accessible, since it replaces to open control. If not, another explicit _close_ control can be added.

cc @porta-antiporta

**Comment by edmullen** [comment]
@porta-antiporta Should an issue be created to implement this, but backlogged / parking-lotted for down the road?

**Comment by porta-antiporta** [comment]
@nickykrause when we get to it; here are some designs for composition of advanced search
