### ISSUE TITLE
Research citation rules for AOs

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#95]
Our research has shown repeatedly – [March workshop conclusions](https://docs.google.com/document/d/11qaoml3hRMRJBt0ygHm3JbxrpEfwFBGPqU1lBM5xcL8/edit) and #86 – that legal users find ability to easily navigate from an AO to cited regulations or cited AOs. The design concepts feature these links in the left rail and were found to be very helpful to people who tried out the design prototype:

![image](https://cloud.githubusercontent.com/assets/2654503/15160324/2202e940-16c7-11e6-9bff-863919b5b2cf.png)

**Task:** Explore which references to a regulation or other advisory opinion should count as a citation. Prior work has indicated that the citations present in a final opinion are legally relevant while those proposed in public comments are frequently not.

**Comment by edmullen** [comment]
### Questions about citations in Advisory Opinions (AO)

**1. Which of the following document types should be parsed to determine what references to regulations or advisory opinions should be considered citations for the AO as a whole?**
```
0,"Final Opinion"
1,"AO Request, Supplemental Material, and Extensions of Time"
2,"Draft Documents"
3,"Withdrawal of Request"
4,"Comments and Ex parte Communications"
5,"Commissioner Statements"
6,"Votes"
```

**2. In a situation like AO 2015-03, which ends without approving a decision, is there a problem with including the references to the U.S.C, which discuss the FEC voting rules rather than the regs that refer to subject of the AO request.**

**3. Are there any other issues related to citations that should be considered?**

**Comment by porta-antiporta** [comment]
commenting to get updates in email

**Comment by edmullen** [comment]
@chemsley Could you take a look at the three questions about and provide guidance? Please reach out with any questions. Thanks!

cc @akort @porta-antiporta

**Comment by AmyKort** [comment]
Thanks for your patience! 

1. For the purposes of this page, we were thinking that the box should only provide links to regulations included in the final AO. The box should probably be labeled "Final AO" in that case. It seems potentially confusing to have citations from other materials in the box. You could still find a reference to a particular citation that appeared in a draft AO if you searched for the citation in the integrated search system--right?

2. In a case where the Commission does not reach agreement on an AOR, the Commission sends out a letter to that effect. This letter will most likely have citations in it. We think that for these types of AO files, the citation box should show the citations included in that final letter.

3. We think that the citations box should include links to other AOs cited in the final option. We'd also like to see links to other AOs that cite the opinion (that way, you have the full story of related opinions that have come before and after the one you are looking at).

**Comment by porta-antiporta** [comment]
Thanks all for the feedback.  A new issue will be created for the design and implementation (will link here when it is available)
