### ISSUE TITLE
Clarify Final Opinion button on AO canonical page

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#97]
There have been a few instances where confusion arose over the final opinion button and the link to the final opinion in the table of documents on the Advisory Opinion canonical page. 

![image](https://cloud.githubusercontent.com/assets/2654503/15154122/0fbe5408-16aa-11e6-9dd6-02df1d442a8d.png)

The button is intended as a redundant link to ensure the user doesn't miss the most important document on the page, but because the button has little info, people can't judge if it's the same doc or different.

Related: https://github.com/18F/fec-eregs/issues/86#issuecomment-218208320

**Comment by porta-antiporta** [comment]
Implemented download button in inital ao release.
