### ISSUE TITLE
Add help text to AO search text field

### ISSUE THREAD

**Issue by edmullen** [18F/fec-eregs#98]
Two small requests for the [Advisory Opinion search field](https://fec-web-adborden.18f.gov/legal/advisory-opinions/):

1. Change "Search Terms" label on the AO search input to "Terms"
2. Add hint text to field reading, "Search keywords, AO number, etc."

Issue exposed in https://github.com/18F/fec-eregs/issues/86#issuecomment-218208320

**Comment by jenniferthibault** [comment]
I think this has been resolved in different ways by recent changes to the AO landing page:

![screen shot 2016-10-20 at 12 54 16 pm](https://cloud.githubusercontent.com/assets/11636908/19569625/6ef2cc02-96c4-11e6-94ac-1753d6f00968.png)

and an upcoming change to the AO filter panel with different content design. (cc @emileighoutlaw )

![screen shot 2016-10-20 at 12 55 25 pm](https://cloud.githubusercontent.com/assets/11636908/19569656/8e42f7e4-96c4-11e6-9f5b-a509a8909dd9.png)
